### ISSUE TITLE
azure_rm_storageblob returns error when trying to download a blob

### ISSUE THREAD

**Issue by JulienPlantier** [ansible/ansible_collections_azure#1015]
##### SUMMARY
Using azure_rm_storageblob to download a blob exits in error with version 1.14 of azure collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_storageblob

##### ANSIBLE VERSION
```
ansible [core 2.13.5]
  config file = /home/ubuntu/ansible/test/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.pyenv/versions/3.8.10/envs/ansible-test2/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.pyenv/versions/ansible-test2/bin/ansible
  python version = 3.8.10 (default, Jun 27 2022, 11:26:32) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection         Version
------------------ -------
azure.azcollection 1.14.0
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/home/ubuntu/ansible/test/ansible.cfg) = ['/home/ubuntu/ansible/test/roles']
DEFAULT_STDOUT_CALLBACK(/home/ubuntu/ansible/test/ansible.cfg) = debug
HOST_KEY_CHECKING(/home/ubuntu/ansible/test/ansible.cfg) = False
INVENTORY_ENABLED(/home/ubuntu/ansible/test/ansible.cfg) = ['ini']
```

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE

Create a storage account, a test container and upload a test.zip file then run the following play
```
---
- hosts: localhost
  name: Test
  tasks:
    - name: Download from Azure Blob
      azure.azcollection.azure_rm_storageblob:
        resource_group: rgname
        storage_account_name: storagename
        container: test
        blob: test.zip
        dest: ./test.zip
      delegate_to: localhost
      become: False
```

##### EXPECTED RESULTS
File is downloaded and ansible run exits in success.

##### ACTUAL RESULTS
File is downloaded but the ansible run exceptions with the following stack trace
```
TASK [Download from Azure Blob] ************************************************************************************************************************************************************************************************************
task path: /home/ubuntu/ansible/test/main.yml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708 `" && echo ansible-tmp-1667554951.9511242-29403-119073228271708="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708 `" ) && sleep 0'
Using module file /home/ubuntu/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py
<localhost> PUT /home/ubuntu/.ansible/tmp/ansible-local-29271qtoc_eh4/tmp9oxq68bd TO /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/ /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 273, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
TypeError: __init__() got an unexpected keyword argument 'encoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', _modlib_path=modlib_path),
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 644, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 640, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 253, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 473, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1513, in exit_json
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1507, in _return_formatted
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1456, in jsonify
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 280, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 267, in _json_encode_fallback
TypeError: Cannot json serialize bytearray(b'\xc4n\x17\x03N\xf3\xf9&\xd6~\x01S\x17\xbd\xd8\xb1')
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 273, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
TypeError: __init__() got an unexpected keyword argument 'encoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', _modlib_path=modlib_path),
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 644, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 640, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 253, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 473, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1513, in exit_json
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1507, in _return_formatted
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1456, in jsonify
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 280, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 267, in _json_encode_fallback
TypeError: Cannot json serialize bytearray(b'\xc4n\x17\x03N\xf3\xf9&\xd6~\x01S\x17\xbd\xd8\xb1')
```

**Comment by vijayreddiar** [comment]
I was about to report, thanks @JulienPlantier for raising it.
@Fred-sun In AWX-EE, unable to use previous working version 1.13.0 through _collections/requirements.yml_ , hence the functionality started failing as soon as 1.14.0 released.

**Comment by vijayreddiar** [comment]
As of now, I managed with this workaround.
```
---
- hosts: localhost
  name: Test

  tasks:

    - name: To capture and ignore specific exception
    # https://github.com/ansible-collections/azure/issues/1015
      block:
        
        - name: Download from Azure Blob
          azure.azcollection.azure_rm_storageblob:
            resource_group: rgname
            storage_account_name: storagename
            container: test
            blob: test.zip
            dest: ./test.zip
          delegate_to: localhost
          become: False
          register: azure_blob_download_stats

      rescue:

        - name: Fail for exceptions other than issue 1015
          ansible.builtin.assert:
            that:
              - azure_blob_download_stats.exception is defined
              - azure_blob_download_stats.exception is search("_json_encode_fallback")
            fail_msg: "Blob failed to download"
            success_msg: "Blob downloaded"
```

**Comment by vasdee** [comment]
Am experiencing this problem myself. Tried with 1.13.5 then thought it might be fixed with 1.14.0 but same problem exists in both versions.

Further to @vijayreddiar workaround, I notice that the file is successfully downloaded, regardless of the error

edit: using python 3.10 if that helps

**Comment by ebdxflr** [comment]
having this issue since the 1.14 upgrade. it happens at random, some downloads work and some return this error. can this be addressed?

**Comment by Fred-sun** [comment]
@ebdxflr Because I haven't encountered your mistake, I can't fix it quickly for the time being! Thanks!

**Comment by vasdee** [comment]
@ebdxflr I found that what I thought was random behaviour, was just that the file was previously downloaded, so the second run works as expected. Might be worth confirming that.

**Comment by ebdxflr** [comment]
@vasdee not quite. im running the play on multiple identical VMs (os/packages/vm type) and on a random number of them the play works flawlessly (file wasnt downloaded before) and on one it fails with that exact error.

**Comment by Fred-sun** [comment]
@JulienPlantier There is a problem with the serial number data. What is the data of your 'test.zip'? Thanks!
```e.g.
TypeError: Cannot json serialize bytearra

**Comment by vijayreddiar** [comment]
@Fred-sun I am facing the same issue even for a json file download. Actually, it's an ARM template which is used for a VM creation in Azure. It was working fine till v1.13.0

**Comment by JulienPlantier** [comment]
@Fred-sun test.zip contained a simple text file with "test" in it I think. I tried different type of files and none could be downloaded without ending in error.

**Comment by Fred-sun** [comment]
@JulienPlantier I see. Could you please change the environment to install the latest version and test it? Thanks!

**Comment by JulienPlantier** [comment]
@Fred-sun I just tested with ansible 6.6.0 and azcollection 1.14.0, same error.

**Comment by Fred-sun** [comment]
@JulienPlantier I created an Ubuntu virtual machine. The installation process is as follows and I had no problems! Thanks!
```e.g.
    1  sudo apt update
    2  sudo apt install python3-pip
    3  mkdir .azure
    4  vi .azure/credentials
    5  sudo pip3 install ansible[azure]
    6  ansible-galaxy collection install azure.azcollection
    7  sudo pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
    8  vi task.yml
    9  ansible-playbook  task.yml -vvvv

**Comment by krystian-panek-vmltech** [comment]
I have also this error, recent azure.azcollection, rhel 9.1, python 3.10, ansible 2.11;
I am totally horrified whenever I am trying to upgrade these Azure Ansible modules. I always have some problems :/ 
3 upgrades in the past, 3 errors. whenever I am using AWS modules there are no problems... :/ 

most probably because they are having single boto3 dependency to install, not > 20 :)

**Comment by JulienPlantier** [comment]
@Fred-sun Created a new VM, ran the same commands and I end up with the same error and stack...

**Comment by Fred-sun** [comment]
@JulienPlantier From the point of view of the error, the parameter is encoded incorrectly during the initialization preprocessing. There are two possible causes for this problem. First, the format of the parameter values is incorrect. Second: version incompatibility results. Thanks!

**Comment by vijayreddiar** [comment]
> There are two possible causes for this problem. First, the format of the parameter values is incorrect. Second: version incompatibility results. Thanks!

- Same playbook with this format of the parameter values worked perfectly in earlier version (1.13.0)
- All requirements were installed using below command and still the issue exists, so it's becoming hard to find the mentioned incompatibility.

`sudo pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt`

**Comment by Fred-sun** [comment]
@vijayreddiar Could you please share the result of "pip3 freeze"?

**Comment by vijayreddiar** [comment]
> pip3 freeze

Please find below the results.

```
adal==1.2.7
ansible==2.9.27
applicationinsights==0.11.10
argcomplete==1.12.3
azure-cli-core==2.34.0
azure-cli-telemetry==1.0.6
azure-common==1.1.11
azure-containerregistry==1.0.0
azure-core==1.26.0
azure-graphrbac==0.61.1
azure-identity==1.7.0
azure-keyvault==1.1.0
azure-mgmt-apimanagement==0.2.0
azure-mgmt-authorization==2.0.0
azure-mgmt-automation==1.0.0
azure-mgmt-batch==5.0.1
azure-mgmt-cdn==11.0.0
azure-mgmt-compute==26.1.0
azure-mgmt-containerinstance==9.0.0
azure-mgmt-containerregistry==9.1.0
azure-mgmt-containerservice==20.0.0
azure-mgmt-core==1.3.0
azure-mgmt-cosmosdb==6.4.0
azure-mgmt-datafactory==2.0.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==1.0.0
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-dns==8.0.0
azure-mgmt-eventhub==10.1.0
azure-mgmt-hdinsight==9.0.0
azure-mgmt-iothub==2.2.0
azure-mgmt-keyvault==10.0.0
azure-mgmt-loganalytics==12.0.0
azure-mgmt-managedservices==6.0.0
azure-mgmt-managementgroups==0.2.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==3.0.0
azure-mgmt-network==19.1.0
azure-mgmt-notificationhubs==7.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-privatedns==1.0.0
azure-mgmt-rdbms==10.0.0
azure-mgmt-recoveryservices==2.0.0
azure-mgmt-recoveryservicesbackup==3.0.0
azure-mgmt-redis==13.0.0
azure-mgmt-resource==10.2.0
azure-mgmt-search==8.0.0
azure-mgmt-servicebus==7.1.0
azure-mgmt-sql==3.0.1
azure-mgmt-storage==19.0.0
azure-mgmt-trafficmanager==1.0.0b1
azure-mgmt-web==6.1.0
azure-nspkg==2.0.0
azure-storage==0.35.1
azure-storage-blob==12.11.0
bcrypt==3.2.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cryptography==36.0.2
humanfriendly==10.0
idna==3.3
isodate==0.6.1
Jinja2==3.1.1
jmespath==1.0.0
knack==0.9.0
lxml==4.8.0
MarkupSafe==2.1.1
msal==1.17.0
msal-extensions==0.3.1
msrest==0.7.1
msrestazure==0.6.4
ntlm-auth==1.5.0
oauthlib==3.2.0
packaging==21.3
paramiko==2.10.3
pkginfo==1.8.2
portalocker==1.7.1
psutil==5.9.0
pycparser==2.21
Pygments==2.11.2
PyJWT==2.3.0
PyNaCl==1.5.0
pyOpenSSL==22.0.0
pyparsing==3.0.7
PySocks==1.7.1
python-dateutil==2.8.2
pyvmomi==7.0.3
pywinrm==0.4.2
PyYAML==6.0
requests==2.28.1
requests-ntlm==1.1.0
requests-oauthlib==1.3.1
six==1.12.0
tabulate==0.8.9
typing_extensions==4.1.1
urllib3==1.26.9
xmltodict==0.13.0
```

**Comment by xuzhang3** [comment]
This issue is cause by the `content_md5` in the response was  encoded in hexadecimal. Json deserialize will result in error decode.

<img width="199" alt="image" src="https://user-images.githubusercontent.com/57888764/205255311-0a46cdff-ee08-4e04-b450-4f855e94a86e.png">
