### ISSUE TITLE
collection azure.azcollection 1.14.0: module azure_rm_storageblob: PDF upload functionality is broken

### ISSUE THREAD

**Issue by sorinscheau** [ansible/ansible_collections_azure#1032]
##### SUMMARY

collection azure.azcollection 1.14.0: module azure_rm_storageblob: PDF upload functionality is broken. Worked fine in 1.13.0.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_storageblob
##### ANSIBLE VERSION

```paste below
AWX 21.9.0
ansible [core 2.12.5.post0]
```

##### COLLECTION VERSION

```paste below
ansible.netcommon 4.1.0
ansible.posix 1.4.0
ansible.utils 2.7.0
ansible.windows 1.12.0
awx.awx 21.9.0
azure.azcollection 1.14.0
chocolatey.chocolatey 1.3.1
community.crypto 2.8.1
community.docker 3.2.1
community.general 6.0.1
community.rabbitmq 1.2.3
community.vmware 3.1.0
community.windows 1.11.1
f5networks.f5_modules 1.21.0
kubernetes.core 2.3.2
voyager.awx 0.2.9 
```

##### CONFIGURATION

```paste below
config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

##### STEPS TO REPRODUCE

```yaml
 - name: Upload the reports to azure blob
      azure.azcollection.azure_rm_storageblob:
        blob: "{{ pdfname }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant_id }}"
        subscription_id: "{{ azure_blob.subscription_id }}"
        container: "{{ azure_blob.container }}"
        force: true
        resource_group: "{{ azure_blob.resource_group }}"
        src: "{{ work_dir }}/{{ pdfname }}"
        state: present
        storage_account_name: "{{ azure_blob.storage_account_name | hash('md5') | truncate(24, True, '') }}"
```

##### EXPECTED RESULTS

PDF file should be uploaded to Azure Blob

##### ACTUAL RESULTS

file gets uploaded but following error appears

```paste below
Traceback (most recent call last):  
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py"
  , line 273, in jsonify  
  File "/usr/lib64/python3.8/json/__init__.py"
  , line 234, in dumps
  return cls(
  TypeError: __init__() got an unexpected keyword argument 'encoding'
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
  File "<stdin>", line 107, in <module>  
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
  return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 644, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 640, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 253, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 473, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1518, in exit_json
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1512, in _return_formatted
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1461, in jsonify
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 280, in jsonify
  File "/usr/lib64/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib64/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_gf6rle8x/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 267, in _json_encode_fallback
TypeError: Cannot json serialize bytearray(b'\\x0f=\\x92\\xdc\\xbb\\xd6\\xfcT\\x8c0J^\\x15J\\xa1\\xce')
```

**Comment by Fred-sun** [comment]
@sorinscheau I installed version 1.14.0 locally for testing and did not encounter your problem? Could you please change the environment or provide the file you want to upload for me to try? Thank you very much!

**Comment by Fred-sun** [comment]
@sorinscheau From the point of view of the error, the parameter is encoded incorrectly during the initialization preprocessing. There are two possible causes for this problem. First, the format of the parameter values is incorrect. Second: version incompatibility results. Thanks!

**Comment by xuzhang3** [comment]
Similar to #1015 Json deserialize /serialize  error. This could be Json cannot serialize the type of the corresponding parameter, we should convert to the right type  before  deserialize /serialize
