### ISSUE TITLE
Authenticating with credential_file doesn't work

### ISSUE THREAD

**Issue by decipher07** [ansible/ansible_collections_azure#1089]
##### SUMMARY

Hey Team, 
I'm facing issues with authenticating azure using "credential_file" for auth_source. Previously, I was able to work with auth_source: cli, but I wish to have everything via "credential_file" under ~/.azure/credentials

I signed out of my azure-cli login and I've referred multiple issues with #548 #871 #446 #279 but none of them is able resolve the issue of using credential_file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
My playbook is a basic account info module: 

```
      azure.azcollection.azure_rm_account_info:
        auth_source: credential_file
```

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/dejain/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/dejain/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
azure.azcollection 1.14.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg

# Since Ansible 2.12 (core):
# To generate an example config file (a "disabled" one with all default settings, commented out):
#               $ ansible-config init --disabled > ansible.cfg
#
# Also you can now have a more complete file by including existing plugins:
# ansible-config init --disabled -t all > ansible.cfg

# For previous versions of Ansible you can check for examples in the 'stable' branches of each version
# Note that this file was always incomplete  and lagging changes to configuration settings

# for example, for 2.9: https://github.com/ansible/ansible/blob/stable-2.9/examples/ansible.cfg

```

##### OS / ENVIRONMENT

```
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"

```

##### STEPS TO REPRODUCE

```yaml
--- # Get facts for the user
- name: Checking working of Azure CLI
  hosts: localhost
  tasks:
    - name: Get Information for Azure Group
      azure.azcollection.azure_rm_account_info:
        auth_source: credential_file
```

My Credential File is as follows:
```
cat ~/.azure/credentials

[default]
subscription_id=
client_id=
secret=
tenant=

```

##### Error RESULTS

```paste below
TASK [Get Information for Azure Group] ****************************************************************************************************************************************************************************
task path: /home/dejain/Desktop/AAP/Azure/githubissue.yml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dejain
<127.0.0.1> EXEC /bin/sh -c 'echo ~dejain && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dejain/.ansible/tmp `"&& mkdir "` echo /home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441 `" && echo ansible-tmp-1677045378.450227-236107-199973210155441="` echo /home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441 `" ) && sleep 0'
Using module file /home/dejain/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py
<127.0.0.1> PUT /home/dejain/.ansible/tmp/ansible-local-235962ip4eh2u5/tmpdzc2tozl TO /home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/ /home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.9 /home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py", line 107, in <module>
    _ansiballz_main()
  File "/home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_account_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_account_info', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py", line 224, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py", line 220, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py", line 132, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py", line 140, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py", line 176, in list_items
IndexError: list index out of range
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/dejain/.ansible/tmp/ansible-tmp-1677045378.450227-236107-199973210155441/AnsiballZ_azure_rm_account_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_account_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_account_info', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py\", line 224, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py\", line 220, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py\", line 132, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py\", line 140, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_account_info_payload_xs0megkv/ansible_azure.azcollection.azure_rm_account_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_account_info.py\", line 176, in list_items\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}


```

**Comment by Fred-sun** [comment]
@decipher07 Thanks for your question.Now,  All ad relate module only support azure-cli credential. Thanks you very much!

**Comment by Fred-sun** [comment]
@decipher07 If you have no other comments, I will closed it! Thank you very much!

**Comment by decipher07** [comment]
Thanks for the help @Fred-sun !
