### ISSUE TITLE
azure_rm_resourcegroup_info throws exception 

### ISSUE THREAD

**Issue by oldskoolsig** [ansible/ansible_collections_azure#1111]
##### SUMMARY

I'm attempting to use a service principal with azure.azcollection.azure_rm_resourcegroup_info to get information about a resource group.

However, when the task is being executed, it fails and dumps and I'm presented with a trace.

While troubleshooting, I've tried the following:

Setting the auth_source to a credential_file and verified that I have the details for the service principal in ~/.azure/credentials.
Passing the values by exporting the variables and then running the play, but all attempts fail in the same way.
As an example:
export AZURE_SUBSCRIPTION_ID=''; export AZURE_CLIENT_ID=''; export AZURE_SECRET=''; export AZURE_TENANT=''; ansible-playbook -i ~/azcreaterg_inventory ansible_module_create_rg.yml -e custom_name="teamsbot" --ask-vault-password -vvv.

It does not appear that authentication is even being attempted, but the task appears to fail when the object is being constructed.

Not sure if it's just something simple I'm overlooking.

I have used the service principal with the command module to perform an az login, so I know there is no issue with the service principal.

I opened: https://github.com/ansible/ansible/issues/80245; however, was informed that this issue should have been created under ansible-collections/azure. The issue was closed. I'm attempting to open here.

Thanks for looking!

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_resourcegroup_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = None
  configured module search path = ['/Users/j8683/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/j8683/Library/Python/3.9/lib/python/site-packages/ansible
  ansible collection location = /Users/j8683/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/j8683/Library/Python/3.9/bin/ansible
  python version = 3.9.6 (default, Sep 26 2022, 11:37:49) [Clang 14.0.0 (clang-1400.0.29.202)] (/Library/Developer/CommandLineTools/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
azure.azcollection 1.14.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None

```

##### OS / ENVIRONMENT

Darwin LTC9RRVQM29G" 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct 9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

##### STEPS TO REPRODUCE

Storing my client_id {{ sp }}, subscription_id {{ sub_id }}, secret {{ secret }}, and tenant {{ tenant }} in a file I encrypted using Ansible Vault.

Decrypting using the task "read secret".

Using in the task: "check if the rg already exists"

Executing the playbook using: ansible-playbook -i /azcreaterg_inventory ansible_module_create_rg.yml -e custom_name="teamsbot" --vault-password-file=/spsecretpass -vvv

```yaml
- name: read secret

  include_vars:

    file: ../files/spsecret

  no_log: true

- name: check if the rg already exists

  azure.azcollection.azure_rm_resourcegroup_info:

    name: "np-{{ custom_name }}-rg-east"

    subscription_id: "{{ sub_id }}"

    client_id: "{{ sp }}"

    secret: "{{ secret }}"

    tenant: "{{ tenant }}"

  register: rg_exists

```

##### EXPECTED RESULTS

custom_name is being specified as: "teamsbot".

np-teamsbot-rg-east is a resource group that exists in the subscription, so I expect the azure.azcollection.azure_rm_resourcegroup_info to retrieve the details about "np-teamsbot-rg-east", storing the data in: rg_exists.

##### ACTUAL RESULTS

The first task works as expected, the file is decrypted and variables read.
The 2nd task results in the underlying Python code throws the traceback (below) to the screen.

The full traceback is:

Traceback (most recent call last):

  File "/Users/j8683/.ansible/tmp/ansible-tmp-1678891419.194826-50522-78867749364726/AnsiballZ_azure_rm_resourcegroup_info.py", line 107, in <module>

    _ansiballz_main()

  File "/Users/j8683/.ansible/tmp/ansible-tmp-1678891419.194826-50522-78867749364726/AnsiballZ_azure_rm_resourcegroup_info.py", line 99, in _ansiballz_main

    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)

  File "/Users/j8683/.ansible/tmp/ansible-tmp-1678891419.194826-50522-78867749364726/AnsiballZ_azure_rm_resourcegroup_info.py", line 47, in invoke_module

    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', _modlib_path=modlib_path),

  File "/opt/homebrew/Cellar/pyt...@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 224, in run_module

    return _run_module_code(code, init_globals, run_name, mod_spec)

  File "/opt/homebrew/Cellar/pyt...@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code

    _run_code(code, mod_globals, init_globals,

  File "/opt/homebrew/Cellar/pyt...@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 235, in <module>

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 231, in main

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 160, in __init__

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 174, in exec_module

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 194, in get_item

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1070, in rm_client

  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_52xvp3bz/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 920, in get_mgmt_svc_client

TypeError: ResourceManagementClient.__init__() missing 1 required positional argument: 'credential'.

```paste below
ansible-playbook -i /azcreaterg_inventory ansible_module_create_rg.yml -e custom_name="teamsbot" --vault-password-file=/spsecretpass -vvv

```

**Comment by iherebyresign** [comment]
Hi,

Are you certain you have azcollection 1.14.0? I am facing the same error/stacktrace when using azure.azcollection.azure_rm_resourcegroup to create a rg as of today (worked fine a few days ago). I found there was an update to this collection yesterday, 1.15.0, and we did not specify a version to use which means we would pull the latest. Specifying version 1.14.0 in our requirements.yml resolved the problem, which led me to believe it is a bug in the latest release.

**Comment by iherebyresign** [comment]
Stack trace:

`"exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1679076035.311163-26-45243489953659/AnsiballZ_azure_rm_resourcegroup.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1679076035.311163-26-45243489953659/AnsiballZ_azure_rm_resourcegroup.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1679076035.311163-26-45243489953659/AnsiballZ_azure_rm_resourcegroup.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_x91j_tbd/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 286, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_x91j_tbd/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 282, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_x91j_tbd/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 162, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_x91j_tbd/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_x91j_tbd/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup.py\", line 178, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_x91j_tbd/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1101, in rm_client\n  File \"/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_x91j_tbd/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 950, in get_mgmt_svc_client\nTypeError: __init__() got an unexpected keyword argument 'credential'`

**Comment by akira6592** [comment]
Hello @oldskoolsig  @iherebyresign .

I also reproduced it with `azure.azcollection` version  1.15.0  `azure_rm_resourcegroup` and `azure_rm_resourcegroup_info` module.

And when I installed python packages with `requirements-azure.txt` for 1.15.0, it resolved.

**Comment by oldskoolsig** [comment]
Thanks @akira6592  - I will give that a try. I'm not familiar with using requirements-azure. txt.
Could you note the steps & commands used? I found this site; https://learn.microsoft.com/en-us/visualstudio/python/managing-required-packages-with-requirements-txt?view=vs-2022 however, not sure if that's saying the same thing...

**Comment by oldskoolsig** [comment]
> Hi,
> 
> Are you certain you have azcollection 1.14.0? I am facing the same error/stacktrace when using azure.azcollection.azure_rm_resourcegroup to create a rg as of today (worked fine a few days ago). I found there was an update to this collection yesterday, 1.15.0, and we did not specify a version to use which means we would pull the latest. Specifying version 1.14.0 in our requirements.yml resolved the problem, which led me to believe it is a bug in the latest release.

I'm certain. That said, it sounds like @akira6592 has been able to repro and resolve. I'm going to try out the requirements-azure.txt approach and see how it goes.

**Comment by Fred-sun** [comment]
@oldskoolsig Yes, the dependencies on azure_rm_resourcegroup_info.py were updated in version 1.15.0, and the required 'credentials' in the api changed to 'credential ', which you can fix by upgrading. Thank you very much!

**Comment by akira6592** [comment]
@oldskoolsig 

from [README.md](https://github.com/ansible-collections/azure#requirements):

>Install dependencies required by the collection (adjust path to collection if necessary):
> ```
>  pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
> ```

Try it!

**Comment by iherebyresign** [comment]
@akira6592 - how would you accomplish this when using awx kubernetes operator? it seems this update introduces a requirement to use a custom execution environment.

**Comment by Fred-sun** [comment]
@oldskoolsig Any feedback?

**Comment by oldskoolsig** [comment]
Sorry about the delay.

I ran: **pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt**

This is what I see for software managed by pip3:

[j8683@LTC9RRVQM29G" $] pip3 list | grep -i azure
azure-cli-core                    2.34.0
azure-cli-telemetry               1.0.6
azure-common                      1.1.11
azure-containerregistry           1.0.0
azure-core                        1.26.3
azure-graphrbac                   0.61.1
azure-identity                    1.7.0
azure-keyvault                    1.1.0
azure-mgmt-apimanagement          0.2.0
azure-mgmt-authorization          2.0.0
azure-mgmt-automation             1.0.0
azure-mgmt-batch                  5.0.1
azure-mgmt-cdn                    11.0.0
azure-mgmt-compute                26.1.0
azure-mgmt-containerinstance      9.0.0
azure-mgmt-containerregistry      9.1.0
azure-mgmt-containerservice       20.0.0
azure-mgmt-core                   1.3.0
azure-mgmt-cosmosdb               6.4.0
azure-mgmt-datafactory            2.0.0
azure-mgmt-datalake-store         1.0.0
azure-mgmt-devtestlabs            3.0.0
azure-mgmt-dns                    8.0.0
azure-mgmt-eventhub               10.1.0
azure-mgmt-hdinsight              9.0.0
azure-mgmt-iothub                 2.2.0
azure-mgmt-keyvault               10.0.0
azure-mgmt-loganalytics           12.0.0
azure-mgmt-managedservices        6.0.0
azure-mgmt-managementgroups       0.2.0
azure-mgmt-marketplaceordering    0.1.0
azure-mgmt-monitor                3.0.0
azure-mgmt-network                19.1.0
azure-mgmt-notificationhubs       7.0.0
azure-mgmt-nspkg                  2.0.0
azure-mgmt-privatedns             1.0.0
azure-mgmt-rdbms                  10.0.0
azure-mgmt-recoveryservices       2.0.0
azure-mgmt-recoveryservicesbackup 3.0.0
azure-mgmt-redis                  13.0.0
azure-mgmt-resource               10.2.0
azure-mgmt-search                 8.0.0
azure-mgmt-servicebus             7.1.0
azure-mgmt-sql                    3.0.1
azure-mgmt-storage                19.0.0
azure-mgmt-trafficmanager         1.0.0b1
azure-mgmt-web                    6.1.0
azure-nspkg                       2.0.0
azure-storage-blob                12.11.0
msrestazure                       0.6.4

Are those the expected results?

In addition, if I look in software collections managed by ansible-galaxy, I still see we are using 1.14.0:

[j8683@LTC9RRVQM29G" $] ansible-galaxy collection list azure.azcollection

# /Users/j8683/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0 

That said, the playbook is still failing:

The full traceback is:
Traceback (most recent call last):
  File "/Users/j8683/.ansible/tmp/ansible-tmp-1679364151.7002292-29135-222752342602643/AnsiballZ_azure_rm_resourcegroup_info.py", line 107, in <module>
    _ansiballz_main()
  File "/Users/j8683/.ansible/tmp/ansible-tmp-1679364151.7002292-29135-222752342602643/AnsiballZ_azure_rm_resourcegroup_info.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/j8683/.ansible/tmp/ansible-tmp-1679364151.7002292-29135-222752342602643/AnsiballZ_azure_rm_resourcegroup_info.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', _modlib_path=modlib_path),
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 235, in <module>
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 231, in main
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 160, in __init__
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 174, in exec_module
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py", line 194, in get_item
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1070, in rm_client
  File "/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 920, in get_mgmt_svc_client
TypeError: ResourceManagementClient.__init__() missing 1 required positional argument: 'credential'
[WARNING]: Platform darwin on host localhost is using the discovered Python interpreter at /opt/homebrew/bin/python3.10, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.14/reference_appendices/interpreter_discovery.html for
more information.
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/opt/homebrew/bin/python3.10"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/j8683/.ansible/tmp/ansible-tmp-1679364151.7002292-29135-222752342602643/AnsiballZ_azure_rm_resourcegroup_info.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/Users/j8683/.ansible/tmp/ansible-tmp-1679364151.7002292-29135-222752342602643/AnsiballZ_azure_rm_resourcegroup_info.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/j8683/.ansible/tmp/ansible-tmp-1679364151.7002292-29135-222752342602643/AnsiballZ_azure_rm_resourcegroup_info.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_resourcegroup_info', _modlib_path=modlib_path),\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py\", line 235, in <module>\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py\", line 231, in main\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py\", line 160, in __init__\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py\", line 174, in exec_module\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_resourcegroup_info.py\", line 194, in get_item\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1070, in rm_client\n  File \"/var/folders/51/76dtk91x4wq1lgdndd_ll6040000gn/T/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload_h9g8zpnn/ansible_azure.azcollection.azure_rm_resourcegroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 920, in get_mgmt_svc_client\nTypeError: ResourceManagementClient.__init__() missing 1 required positional argument: 'credential'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

My guess is the failure is due to me still having 1.14.0 of the Azure Collection.

Is there any way to make it use version 1.15?

**Comment by Fred-sun** [comment]
@oldskoolsig Try this: ansible-galaxy collection install azure.azcollection --force

**Comment by oldskoolsig** [comment]
@Fred-sun - Excellent! This worked. Thank you for providing information on how to resolve.

I've got a couple follow up questions, I'm understanding the output to indicate that I've got versions 1.14 and 1.15 installed...

[j8683@LTC9RRVQM29G" $]  ansible-galaxy collection list azure.azcollection 

# /Users/j8683/Library/Python/3.9/lib/python/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.14.0 

# /Users/j8683/.ansible/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.15.0 

Is that true? and if so, what's the recommended way to upgrade all paths to have 1.15?

Also, is this a bug with version 1.14? or if not, is it more of a conflict between the version of the collection I had (1.14) and the version of Python I have installed?

Thanks!

**Comment by Fred-sun** [comment]
@oldskoolsig This is not a Bug because we upgraded all SDK1s to SDK2 in order to differentiate the new releases. Thank you very much!

**Comment by oldskoolsig** [comment]
@Fred-sun Thanks again!
