### ISSUE TITLE
Azure modules need support for left/right single quotes

### ISSUE THREAD

**Issue by Sneedes** [ansible/ansible_collections_azure#114]
##### SUMMARY
Utilizing the azure_rm_virtualmachine module.  
Receive the following error from Ansible in the stderr:
`UnicodeEncodeError: 'ascii' codec can't encode character u'\\\\u2018' in position 596: ordinal not in range(128)\\n`

https://github.com/ansible/ansible/issues/67358

Noting that the **actual** Azure error message reported is believed to be along the lines of:
`
Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: eastus, Current Limit: 350, Current Usage: 346, Additional Required: 8, (Minimum) New Limit Required: 354. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%222b66c83b-5e20-4ee0-a2e2-4ba091559f95%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ‘Details’ section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests.`

Note that the error message from Azure includes left/right single quotes (hex U+2018 and U+2019).  The fancy quotes are around the word **Details** in the 2nd to last sentence.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine module
Suspect this could apply to any/all Azure modules.  

##### ANSIBLE VERSION
```
ansible 2.10.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/azure-20200212/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/azure-20200212/bin/ansible
  python version = 2.7.5 (default, Jun 11 2019, 14:33:56) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
No changes/default config.

##### OS / ENVIRONMENT
Ansible Tower ; RHEL 7.7 control nodes.
Azure Cloud Module(s)

##### STEPS TO REPRODUCE

In my case, used azure_rm_virtualmachine to create an Azure VM.  The Azure Subscription had quotas in place that prevented the VM from being created.  Azure believed to generate an error message to be _read_ by Ansible.  However, the Azure message/output contains unicode punctuation (left-quote and right-quote; u2018 and u02019).  

These left-quote and right-quote characters result in the **UnicodeEncodeError: 'ascii' codec can't encode character** reported by Ansible.

##### EXPECTED RESULTS
Expect that Azure error messages be reported via Ansible modules.  Expect to not need to obtain a nonsensical/ASCII error, then navigate to Azure to determine the **actual** error.  

##### ACTUAL RESULTS
```
TASK [azure_provision_linux_vm : Create Azure VM azrs95056] ********************
task path: /var/lib/awx/projects/_273__azure_provision_linux_vm/roles/azure_provision_linux_vm/tasks/main.yml:95
[

<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: awx
[
<127.0.0.1> EXEC /bin/sh -c 'echo ~awx && sleep 0'
[
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879 `" && echo ansible-tmp-1581531670.25-176907752234879="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879 `" ) && sleep 0'
[
Using module file /opt/ansible/azure-20200212/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
[
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-7JRYNDn/tmppZnixX TO /var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py
[
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/ /var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py && sleep 0'
[
<127.0.0.1> EXEC /bin/sh -c '/opt/ansible/azure-20200212/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py && sleep 0'
[
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/ > /dev/null 2>&1 && sleep 0'
[
The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_virtualmachine', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 2203, in <module>
  File "/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 2199, in main
  File "/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 899, in __init__
  File "/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 417, in __init__
  File "/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 1440, in exec_module
  File "/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 1970, in create_or_update_vm
  File "/opt/ansible/azure-20200212/lib/python2.7/site-packages/msrestazure/azure_exceptions.py", line 193, in __str__
    return str(self.error)
  File "/opt/ansible/azure-20200212/lib/python2.7/site-packages/msrestazure/azure_exceptions.py", line 89, in __str__
    error_str += "\\nMessage: {}".format(self._message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\\u2018' in position 596: ordinal not in range(128)
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/var/lib/awx/.ansible/tmp/ansible-tmp-1581531670.25-176907752234879/AnsiballZ_azure_rm_virtualmachine.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_virtualmachine', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 176, in run_module\\n    fname, loader, pkg_name)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 82, in _run_module_code\\n    mod_name, mod_fname, mod_loader, pkg_name)\\n  File \\"/usr/lib64/python2.7/runpy.py\\", line 72, in _run_code\\n    exec code in run_globals\\n  File \\"/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\\", line 2203, in <module>\\n  File \\"/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\\", line 2199, in main\\n  File \\"/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\\", line 899, in __init__\\n  File \\"/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py\\", line 417, in __init__\\n  File \\"/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\\", line 1440, in exec_module\\n  File \\"/tmp/ansible_azure_rm_virtualmachine_payload_qkU1Tx/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\\", line 1970, in create_or_update_vm\\n  File \\"/opt/ansible/azure-20200212/lib/python2.7/site-packages/msrestazure/azure_exceptions.py\\", line 193, in __str__\\n    return str(self.error)\\n  File \\"/opt/ansible/azure-20200212/lib/python2.7/site-packages/msrestazure/azure_exceptions.py\\", line 89, in __str__\\n    error_str += \\"\\\\nMessage: {}\\".format(self._message)\\n
	UnicodeEncodeError: 'ascii' codec can't encode character u'\\\\u2018' in position 596: ordinal not in range(128)\\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", 
    "rc": 1
}
[

```

**Comment by Fred-sun** [comment]
@Sneedes Thank you for taking the time to report this issue, can you provide your playbook? Thank you!

**Comment by Sneedes** [comment]
At the moment, I cannot re-test/confirm this issue.  The subscription/resource groups that I have access to now all have currently all have sufficiently sized quotas for **Total Regional vCPUs** and **Standard DSv2 Family vCPUs**.  These quotas were increased once we found the root cause to failed Azure VM deployments from Ansible.  

In order to test/confirm, one would need to attempt to provision a new VM via the **azure_rm_virtualmachine** module that exceeds either the Total Regional vCPUs or Standard DSv2 Family vCPUs values.  I do not have the access/rights to setup a new subscription/resource group with a very small quota where I could easily exceed the Azure quotas.

Azure Portal > _Select Desired Subscription_ > Usage + Quotas > Provider = Microsoft.Compute

The error messages / output / return codes from Azure contain _smart_ quotes.
Note the difference between:
“smart/non-ascii quotes”
"ascii quotes"

These non-ASCII characters cause the Ansible module to fail unexpectedly.

An example snippet of Ansible to provision a VM would be something along the lines of:

```
- name: "Create Azure VM {{ my_vm_name | lower }}"
  azure_rm_virtualmachine:
    name: "{{ my_vm_name | lower }}"
    resource_group: "{{ my_vm_rg }}"
    vm_size: "{{ my_vm_size }}"
    managed_disk_type: "{{ my_vm_os_disk_type }}"
    admin_username: "{{ my_vm_admin_username }}"
    ssh_password_enabled: no
    ssh_public_keys:
      - path: "/home/{{ my_vm_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ my_vm_admin_ssh_key }}"
    network_interface_names: "{{ my_vm_name | lower }}-nic1"
    os_disk_size_gb: "{{ my_vm_os_disk_size_gb | default(omit) }}"
    image: "{{ my_vm_image }}"
    plan: "{{ my_vm_plan | default(omit) }}"
    availability_set: "{{ my_vm_availability_set | default(omit) }}"

```

**Comment by Fred-sun** [comment]
Judging from the error message above, this is not an issue with ansible. It seems more like a quota problem with your credentials. Thank you!

**Comment by Sneedes** [comment]
The root cause was absolutely a quota issue with Azure.  

HOWEVER, because of the ASCII vs. Non-ASCII "Smart Quotes" from the data returned from Azure, the Ansible module did not fail gracefully nor indicate any kind of issue with Azure quota.  Instead failed with some kind of unicode/quote (not quota) issue.

Unsure if this is still duplicatable.
Issue is very old; back on Ansible 2.10 (prior to ansible-core with more rapidly developing azure.azcollections and associated pip modules.  

I cannot easily attempt to reproduce in my environment as I lack permissions to modify quotas and such.

**Comment by Fred-sun** [comment]
I want to cooperate with the investigation to find out this problem. Could you describe in detail how this problem was discovered? If possible, provide as much information as possible and execute use cases. Thank you!

**Comment by Fred-sun** [comment]
@Sneedes As mentioned above, the fundamental cause of this problem is the issue of quotas. With the development of Azure service, the returned information should have also been optimized. When we encounter the issue of quotas again, the error message prompted is as follows, very clear.
```e.g.
Operation could not be completed as it results in exceeding approved standardDSv3Family Cores quota.
```
So I will close this question. If you have any questions, you are welcome to submit them and we will conduct a thorough investigation. Thank you!
