### ISSUE TITLE
Unable to perform certain actions(eg:Add User to Azure AD Group) from the collection and its failing with an error "azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation." 

### ISSUE THREAD

**Issue by amarmh** [ansible/ansible_collections_azure#1165]
##### SUMMARY
Unable to perform certain actions(eg:Add User to Azure AD Group) from the collection and its failing with an error "azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation." 

Collections - 
Red Hat : https://console.redhat.com/ansible/automation-hub/repo/published/azure/azcollection/content/module/azure_rm_adgroup/
Galaxy : https://galaxy.ansible.com/azure/azcollection?extIdCarryOver=true&sc_cid=701f2000001OH6kAAG

Traceback:
~~~
  "exception": "Traceback (most recent call last):
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 307, in exec_module
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 332, in update_members
    File \"/usr/local/lib/python3.9/site-packages/azure/graphrbac/operations/groups_operations.py\", line 213, in add_member
      raise models.GraphErrorException(self._deserialize, response)
  azure.graphrbac.models.graph_error_py3.GraphErrorException: Insufficient privileges to complete the operation.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File \"/home/runner/.ansible/tmp/ansible-tmp-1683110261.8100598-64-255307998344458/AnsiballZ_azure_rm_adgroup.py\", line 107, in <module>
      _ansiballz_main()
    File \"/home/runner/.ansible/tmp/ansible-tmp-1683110261.8100598-64-255307998344458/AnsiballZ_azure_rm_adgroup.py\", line 99, in _ansiballz_main
      invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
    File \"/home/runner/.ansible/tmp/ansible-tmp-1683110261.8100598-64-255307998344458/AnsiballZ_azure_rm_adgroup.py\", line 47, in invoke_module
      runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', _modlib_path=modlib_path),
    File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module
      return _run_module_code(code, init_globals, run_name, mod_spec)
    File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code
      exec(code, run_globals)
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 443, in <module>
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 439, in main
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 263, in __init__
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 312, in exec_module
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 505, in fail
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py\", line 1533, in fail_json
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py\", line 1506, in _return_formatted
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py\", line 928, in remove_values
    File \"/tmp/ansible_azure_rm_adgroup_payload__y9_azew/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py\", line 471, in _remove_values_conditions
  TypeError: Value of unknown type: <class 'azure.graphrbac.models.graph_error_py3.GraphErrorException'>, Insufficient privileges to complete the operation.
  ",
  "msg": "MODULE FAILURE
  See stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": null,
  "changed": false
~~~

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module > azure_rm_adgroup

##### ANSIBLE VERSION

```
ansible-playbook [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
azure.azcollection 1.15.0
```

##### OS / ENVIRONMENT
RHEL 8 and Azure AD

##### STEPS TO REPRODUCE
```
---
- name: Add User to Azure AD Group
  hosts: localhost
  gather_facts: false
  collections:
    - azure.azcollection
  vars:
    subscription_id: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"
    client_id: "{{ lookup('env','AZURE_CLIENT_ID') }}"
    secret: "{{ lookup('env','AZURE_SECRET') }}"
    tenant: "{{ lookup('env','AZURE_TENANT') }}"
    proxy_env:
      https_proxy: http://proxy.example.com8080/
    group_object_id: ''
    user_object_id: ''

  tasks:
    - name: Get group info
      azure_rm_adgroup_info:
        attribute_name: "displayName"
        attribute_value: "{{ group_name }}"
        tenant: "{{ tenant }}"
      register: group_info
      ignore_errors: true 

    - name: Fail error if no group found
      fail:
        msg: "[ERROR] - Group '{{ group_name }}' not found in Azure AD"
      when: group_info.ad_groups[0].object_id is not defined
      
    - name: Get user info
      azure_rm_aduser_info:
        attribute_name: "displayName"
        attribute_value: "{{ user_name }}"
        tenant: "{{ tenant }}"
      register: user_info
      ignore_errors: true

    - name: Fail error if no user found
      fail:
        msg: "[ERROR] - User '{{ user_name }}' not found in Azure AD"
      when: user_info.ad_users[0].object_id is not defined
    
    - name: Ensure user is member of the group 
      azure_rm_adgroup:
        object_id: "{{ group_info.ad_groups[0].object_id }}"
        tenant: "{{ tenant }}"
        present_members:
          - "[https://graph.windows.net/{{](https://graph.windows.net/%7B%7B) tenant }}/directoryObjects/{{ user_info.ad_users[0].object_id }}"
      environment: "{{proxy_env}}"

    - name: Print Result on Screen
      ansible.builtin.debug:
        msg: "User {{ user_name }} successfully added to {{ group_name }} Azure AD Group "

```

##### EXPECTED RESULTS
Actions with module: `azure_rm_adgroup`  should succeed.

##### ACTUAL RESULTS
```
TASK [Ensure user is member of the group] **************************************
task path: /runner/project/AADAddUserToGroup.yml:61
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/runner/.ansible/tmp `"&& mkdir "` echo /home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556 `" && echo ansible-tmp-1684313458.8127143-82-27220679139556="` echo /home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556 `" ) && sleep 0'
Using module file /usr/share/ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py
<localhost> PUT /home/runner/.ansible/tmp/ansible-local-21ook6xpou/tmpplzytgy5 TO /home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/ /home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'https_proxy=http://proxy.example.com:8080 /usr/bin/python3 /home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 307, in exec_module
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 332, in update_members
  File "/usr/local/lib/python3.9/site-packages/azure/graphrbac/operations/groups_operations.py", line 213, in add_member
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: The URI 'https://graph.windows.net/v1.0/directoryObjects/6e4457a5-4267-4e6a-b9c2-02fc59406de1' is not valid since it is not based on 'https://graph.windows.net/bc5f3009-5bd3-4402-beb1-6e2eb7c68ff2/'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py", line 107, in <module>
    _ansiballz_main()
  File "/home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 443, in <module>
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 439, in main
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 263, in __init__
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 312, in exec_module
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 505, in fail
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py", line 1533, in fail_json
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py", line 1506, in _return_formatted
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py", line 928, in remove_values
  File "/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py", line 471, in _remove_values_conditions
TypeError: Value of unknown type: <class 'azure.graphrbac.models.graph_error_py3.GraphErrorException'>, The URI 'https://graph.windows.net/v1.0/directoryObjects/6e4457a5-4267-4e6a-b9c2-02fc59406de1' is not valid since it is not based on 'https://graph.windows.net/bc5f3009-5bd3-4402-beb1-6e2eb7c68ff2/'.
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\\", line 307, in exec_module\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\\", line 332, in update_members\\n  File \\"/usr/local/lib/python3.9/site-packages/azure/graphrbac/operations/groups_operations.py\\", line 213, in add_member\\n    raise models.GraphErrorException(self._deserialize, response)\\nazure.graphrbac.models.graph_error_py3.GraphErrorException: The URI 'https://graph.windows.net/v1.0/directoryObjects/6e4457a5-4267-4e6a-b9c2-02fc59406de1' is not valid since it is not based on 'https://graph.windows.net/bc5f3009-5bd3-4402-beb1-6e2eb7c68ff2/'.\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\"/home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py\\", line 107, in <module>\\n    _ansiballz_main()\\n  File \\"/home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py\\", line 99, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/home/runner/.ansible/tmp/ansible-tmp-1684313458.8127143-82-27220679139556/AnsiballZ_azure_rm_adgroup.py\\", line 47, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', _modlib_path=modlib_path),\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 225, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 97, in _run_module_code\\n    _run_code(code, mod_globals, init_globals,\\n  File \\"/usr/lib64/python3.9/runpy.py\\", line 87, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\\", line 443, in <module>\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\\", line 439, in main\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\\", line 263, in __init__\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\\", line 472, in __init__\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\\", line 312, in exec_module\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\\", line 505, in fail\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py\\", line 1533, in fail_json\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py\\", line 1506, in _return_formatted\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py\\", line 928, in remove_values\\n  File \\"/tmp/ansible_azure_rm_adgroup_payload_yv4gol2t/ansible_azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py\\", line 471, in _remove_values_conditions\\nTypeError: Value of unknown type: <class 'azure.graphrbac.models.graph_error_py3.GraphErrorException'>, The URI 'https://graph.windows.net/v1.0/directoryObjects/6e4457a5-4267-4e6a-b9c2-02fc59406de1' is not valid since it is not based on 'https://graph.windows.net/bc5f3009-5bd3-4402-beb1-6e2eb7c68ff2/'.\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

```

**Comment by amarmh** [comment]
Analysis from - https://github.com/ansible-collections/azure/issues/869 which appears to be a valid.

~~~
Reviewing docs:

Microsoft is migrating Graph API endpoints:

https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-faq

So from now, API requests must call to another url:

https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences

Checking random code of azcollection:

https://github.com/ansible-collections/azure/blob/dev/plugins/module_utils/azure_rm_common.py

You can find old URL endpoint in the code:

def _get_azure_cli_credentials(self, subscription_id=None, resource=None):
if self.is_ad_resource:
resource = 'https://graph.windows.net/'
subscription_id = subscription_id or self._get_env('subscription_id')

After that, for me it's clear what's going on, the collection must be migrated to Microsoft Graph instead of Azure AD Graph.
~~~

**Comment by Fred-sun** [comment]
@amarmh According to the error report, it is caused by your permission problem. Could you please check whether the account you use has the permission to manage group? Thanks!

**Comment by amarmh** [comment]
@Fred-sun It does work when we do the curl :
```
curl --location --request POST '[https://graph.microsoft.com/v1.0/groups/{group_id}/members/$ref](https://graph.microsoft.com/v1.0/groups/%7Bgroup_id%7D/members/$ref)' \
--header 'Authorization: Bearer {access_token}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "@odata.id": "[https://graph.windows.net/v1.0/directoryObjects/{user_id}](https://graph.windows.net/v1.0/directoryObjects/%7Buser_id%7D)"
}'
```
Is there any possibility that the communication is getting routed to OLD APIs of MS?

I tested this issue in my test env which worked fine, I used $az login for authentication and for authorization the vars mentioned in the description. But this is not working for one of the customers.

**Comment by Fred-sun** [comment]
@amarmh Are you using the same set of credentials? If not, can you confirm whether their sub has access to the group resource? Thank you very much!

**Comment by amarmh** [comment]
Hello Fred, 
Yes, the creds appears to be having the permission to add/remove users from the group.
Below works as a workaround:
~~~
    - name: Use Token
      ansible.builtin.uri:
        url: "https://graph.microsoft.com/v1.0/groups/{{ group_info.ad_groups[0].object_id }}/members/$ref"
        method: POST
        return_content: true
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ login.json.access_token }}" 
        # body: '{ "@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/9baexxx-1840-xxxx-xxxxxxxxxxxx" }'
        # body: '{ "@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/{{ user_info.ad_users[0].object_id }}" }'
        body: '{ "@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/{{ user_info.ad_users[0].object_id | string }}" }'
      register: login
      environment: "{{ proxy_env }}"
     # no_log: true
~~~

**Comment by xuzhang3** [comment]
@amarmh   I tried with a SPN with user read/write permission and I can add  the users to the group.  Is the Bearer Token generated from the same SPN used to run the  ansible script?   `Insufficient privileges to complete the operation` this error msg normally appears to be the SPN does not have the permission.

**Comment by cklingspor** [comment]
I experienced the same issue when attempting to delete an AD group. 
The Service Principal I'm using has the permissions to delete groups. I've verified that using the CLI

**Comment by Fred-sun** [comment]
@amarmh @cklingspor  ADGraphrbac has been migrated to MSGraph and supports Service Pricipals to manage AD resources, you can upgrade to v2.0.0 to try it! Related PR #1325, thanks!
