### ISSUE TITLE
Key Vault Module/Requirements incompatible with python 3.11

### ISSUE THREAD

**Issue by Klaas-** [ansible/ansible_collections_azure#1181]
##### SUMMARY
python 3.11 breaks key vault modules

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_keyvaultsecret_info
azure_rm_keyvaultsecret

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.0]
  config file = /home/username/ansible-env/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/ansible-venv/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/username/ansible-env/collections
  executable location = /home/username/ansible-venv/bin/ansible
  python version = 3.11.2 (main, Feb 17 2023, 09:28:16) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/home/username/ansible-venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
1.16.0
```

##### OS / ENVIRONMENT

RHEL 8.8

##### STEPS TO REPRODUCE

```
mkdir ansible-venv
python3.11 -m venv ansible-venv/
cd ansible-venv/
source bin/activate
python -m pip install ansible
cd ~/ansible-env
python -m pip install -r collections/ansible_collections/azure/azcollection/requirements-azure.txt
```

Run any playbook that uses one of the keyvault modules

##### EXPECTED RESULTS

Keyvault modules work

##### ACTUAL RESULTS

```paste below
Traceback (most recent call last):
  File "/home/username/.ansible/tmp/ansible-tmp-1685973786.2649815-908577-84376837658921/AnsiballZ_azure_rm_keyvaultsecret.py", line 107, in <module>
    _ansiballz_main()
  File "/home/username/.ansible/tmp/ansible-tmp-1685973786.2649815-908577-84376837658921/AnsiballZ_azure_rm_keyvaultsecret.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/username/.ansible/tmp/ansible-tmp-1685973786.2649815-908577-84376837658921/AnsiballZ_azure_rm_keyvaultsecret.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload_18m1q0pc/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py", line 271, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload_18m1q0pc/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py", line 267, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload_18m1q0pc/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py", line 140, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload_18m1q0pc/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload_18m1q0pc/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py", line 184, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload_18m1q0pc/ansible_azure.azcollection.azure_rm_keyvaultsecret_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret.py", line 255, in create_update_secret
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/azure/keyvault/v7_0/key_vault_client.py", line 1627, in set_secret
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/msrest/universal_http/requests.py", line 139, in send
    response = session.request(
               ^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/requests/models.py", line 372, in prepare
    self.prepare_auth(auth, url)
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/requests/models.py", line 603, in prepare_auth
    r = auth(self)
        ^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/azure/keyvault/key_vault_authentication.py", line 76, in __call__
    security = self._get_message_security(request, challenge)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/azure/keyvault/key_vault_authentication.py", line 169, in _get_message_security
    token = AccessToken(*self._callback(challenge.get_authorization_server(),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/ansible-venv/lib64/python3.11/site-packages/azure/keyvault/key_vault_authentication.py", line 61, in _auth_callback_compat
    if len(inspect.getargspec(self._user_callback).args) == 3 \n           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

```

I think you'll need to use a newer keyvault python package . https://github.com/Azure/azure-cli/issues/26398 azure cli was hit by the same problem

**Comment by Klaas-** [comment]
The info module does not throw an error, but it does not actually pass any data; it just shows `"secrets": []` where the same code would lead to a secret with python 3.9

**Comment by Fred-sun** [comment]
@Klaas- This is caused by the change of the inspect function in the built-in module of python3.11. We are still discussing how to solve this problem, thank you!

**Comment by Fred-sun** [comment]
@Klaas- Do you have any good suggestions and modifications? You are also welcome to propose, thank you!

**Comment by Klaas-** [comment]
@Fred-sun my understanding is you need to use a newer azure python sdk. But that means you have to modify the keyvault modules because they did a change upstream between 1.1.0 and 4.2.0 (which would be a current version) see https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/keyvault/azure-keyvault

**Comment by Fred-sun** [comment]
@Klaas- Already update to 4.2.0, relate PR #1198 .

**Comment by Fred-sun** [comment]
Fixed

**Comment by celsocoutinho-tangany** [comment]
I am having this issue on `azure_rm_keyvaultsecret`, on the following setup:

```
$ ansible --version
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/8.2.0_2/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin//ansible
  python version = 3.11.4 (main, Jul 25 2023, 17:36:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/opt/homebrew/Cellar/ansible/8.2.0_2/libexec/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

Any idea how I can dodge this?
