### ISSUE TITLE
ValueError: 'virtual_networks' is not available in API version 2021-03-01

### ISSUE THREAD

**Issue by arnoschuring** [ansible/ansible_collections_azure#1224]
##### SUMMARY

azure_rm_virtualnetwork uses an invalid API version.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualnetwork

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.2]
  config file = None
  configured module search path = ['/home/luser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/luser/ansible-venv/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/luser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/luser/ansible-venv/bin/ansible
  python version = 3.11.3 (main, Apr 27 2023, 22:08:21) [GCC] (/home/luser/ansible-venv/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list community.azure

# /home/luser/ansible-venv/lib/python3.11/site-packages/ansible_collections
Collection      Version
--------------- -------
community.azure 2.0.0

# /home/luser/ansible-venv/lib64/python3.11/site-packages/ansible_collections
Collection      Version
--------------- -------
community.azure 2.0.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
EDITOR(env: EDITOR) = /usr/bin/nvim
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Targeting the Azure public cloud from a Python virtualenv.

##### STEPS TO REPRODUCE

```yaml
  tasks:
  - azure_rm_virtualnetwork:
      resource_group: "insert-existing-resource-group"
      name: "vnet-euw-10.10"
```

##### EXPECTED RESULTS

vnet is created.

##### ACTUAL RESULTS

```paste below
TASK [azure_rm_virtualnetwork] *****************************************************************************************
task path: /mnt/c/Users/arno.schuring/source/repos/003775-pipelines/azure-vnet/minimal.yaml:8
redirecting (type: modules) ansible.builtin.azure_rm_virtualnetwork to azure.azcollection.azure_rm_virtualnetwork
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: luser
<127.0.0.1> EXEC /bin/sh -c 'echo ~luser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/luser/.ansible/tmp `"&& mkdir "` echo /home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756 `" && echo ansible-tmp-1690562136.8677745-1199-281232971225756="` echo /home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.azure_rm_virtualnetwork to azure.azcollection.azure_rm_virtualnetwork
Using module file /home/luser/ansible-venv/lib64/python3.11/site-packages/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py
<127.0.0.1> PUT /home/luser/.ansible/tmp/ansible-local-1195qnov7zfy/tmp49zicezn TO /home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/ /home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/luser/ansible-venv/bin/python3 /home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py", line 107, in <module>
    _ansiballz_main()
  File "/home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualnetwork', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualnetwork', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py", line 409, in <module>
  File "/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py", line 405, in main
  File "/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py", line 250, in __init__
  File "/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 472, in __init__
  File "/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py", line 277, in exec_module
  File "/home/luser/ansible-venv/lib64/python3.11/site-packages/azure/mgmt/network/_validation.py", line 25, in wrapper
    raise ValueError(
ValueError: 'virtual_networks' is not available in API version 2021-03-01. All valid API version are 2015-06-15, 2017-10-01, 2018-04-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-02-01, 2023-02-01.
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/luser/.ansible/tmp/ansible-tmp-1690562136.8677745-1199-281232971225756/AnsiballZ_azure_rm_virtualnetwork.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualnetwork', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualnetwork', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 409, in <module>\n  File \"/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 405, in main\n  File \"/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 250, in __init__\n  File \"/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 472, in __init__\n  File \"/tmp/ansible_azure_rm_virtualnetwork_payload_2gp886an/ansible_azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 277, in exec_module\n  File \"/home/luser/ansible-venv/lib64/python3.11/site-packages/azure/mgmt/network/_validation.py\", line 25, in wrapper\n    raise ValueError(\nValueError: 'virtual_networks' is not available in API version 2021-03-01. All valid API version are 2015-06-15, 2017-10-01, 2018-04-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-02-01, 2023-02-01.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by Fred-sun** [comment]
@arnoschuring Which version of azcollections did you install? Can you share the 'pip3 list' information? Suspect that you have not installed the specified version of azure-mgmt-network（azure-mgmt-network==19.1.0）. Thank you!

**Comment by arnoschuring** [comment]
That may be the cause, what's the canonical starter documentation? I couldn't easily find a howto or similar on setting up an Ansible environment for Azure management so I had to rely on trial-and-error. The backtrace above is with the most recent version (azure-mgmt-network==24.0.0), but I did try various other versions. Apparently not 19.1.0

```
$ pip list |grep -E az\|ans
ansible                           8.2.0
ansible-core                      2.15.2
azure-cli-core                    2.50.0
azure-cli-telemetry               1.0.8
azure-common                      1.1.28
azure-core                        1.28.0
azure-identity                    1.13.0
azure-keyvault-secrets            4.7.0
azure-mgmt-authorization          4.0.0
azure-mgmt-automation             1.0.0
azure-mgmt-compute                30.1.0
azure-mgmt-containerinstance      10.1.0
azure-mgmt-containerregistry      10.1.0
azure-mgmt-containerservice       25.0.0
azure-mgmt-core                   1.4.0
azure-mgmt-datafactory            3.1.0
azure-mgmt-datalake-nspkg         3.0.1
azure-mgmt-datalake-store         0.5.0
azure-mgmt-dns                    8.1.0
azure-mgmt-eventhub               11.0.0
azure-mgmt-iothub                 2.4.0
azure-mgmt-keyvault               10.2.3
azure-mgmt-loganalytics           12.0.0
azure-mgmt-managementgroups       1.0.0
azure-mgmt-marketplaceordering    1.1.0
azure-mgmt-monitor                6.0.1
azure-mgmt-msi                    7.0.0
azure-mgmt-network                24.0.0
azure-mgmt-notificationhubs       8.0.0
azure-mgmt-nspkg                  3.0.2
azure-mgmt-privatedns             1.1.0
azure-mgmt-rdbms                  10.1.0
azure-mgmt-recoveryservicesbackup 3.0.0
azure-mgmt-resource               23.0.1
azure-mgmt-search                 9.0.0
azure-mgmt-servicebus             8.2.0
azure-mgmt-sql                    3.0.1
azure-mgmt-storage                21.0.0
azure-mgmt-trafficmanager         1.1.0
azure-mgmt-web                    7.1.0
azure-nspkg                       3.0.2
azure-storage-blob                12.17.0
msrestazure                       0.6.4
```

azure.azcollection is at 1.16.0:
```
Collection         Version
------------------ -------
azure.azcollection 1.16.0
```

**Comment by Fred-sun** [comment]
@arnoschuring Thank you very much for your reply. First of all, the version we require is azure-mgmt-network=v19.1.0, which supports api=2021-03-01. However, upgrading to azure-mgmt-network=24.0.0 does not support API version v2021-03-01, we recommend that you drop to v19.1.0 and try again. Thank you!

**Comment by arnoschuring** [comment]
I've been able to make it work by using the requirements from here: https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt

But it would have been nice if this file would have been linked from the documentation, rather than having to chase increasingly unhelpful web search results.
