### ISSUE TITLE
azure_rm_adgroup add new members to group broken since 2.0.0 and further

### ISSUE THREAD

**Issue by rooso** [ansible/ansible_collections_azure#1387]
##### SUMMARY
Adding a member to an Azure AD Group throws error since collection version 2.0.0.
Everything works fine until 1.19.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure.azcollection.azure_rm_adgroup:

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/demouser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/demouser/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/demouser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/demouser/.local/bin/ansible
  python version = 3.9.16 (main, Oct 23 2023, 20:10:56) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 2.1.1
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/mnt/data/awx/ansible/projects/awx/inventories/inv.yml']
DEFAULT_INVENTORY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/home/demouser/.ansible/collections/ansible_collections/demo/awx/plugins/inventory']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = ['demo.awx.inv']
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT
Rocky Linux 8

##### STEPS TO REPRODUCE

Create a Playbook and try to add an user to an existing Azure AD group.

```yaml
    - name: add user to remote access group
      azure.azcollection.azure_rm_adgroup:
        tenant: "..."
        client_id: "..."
        secret: "..."
        subscription_id: "..."
        object_id: "..."
        state: present
        present_members:
          - "https://graph.windows.net/..tenant...id.../directoryObjects/...object...id..."
```

##### EXPECTED RESULTS
User is added if not already present in group.

##### ACTUAL RESULTS

Ansible failes with error.

```paste below
TASK [add user to remote access group] *****************************************
task path: /playbooks/user_management.yml:49
Loading collection demo.interfaces from /home/demouser/.ansible/collections/ansible_collections/demo/interfaces
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: demouser
<127.0.0.1> EXEC /bin/sh -c 'echo ~demouser && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/demouser/.ansible/tmp `"&& mkdir "` echo /home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212 `" && echo ansible-tmp-1703856792.0072005-8573-3056020557212="` echo /home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212 `" ) && sleep 0'
Using module file /home/demouser/.local/lib/python3.9/site-packages/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py
<127.0.0.1> PUT /home/demouser/.ansible/tmp/ansible-local-8524v42e_p9e/tmp7mqcpo9q TO /home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/ /home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.9 /home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 302, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 324, in update_members
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 472, in add_group_member
  File "/home/demouser/.local/lib/python3.9/site-packages/msgraph/generated/groups/item/members/ref/ref_request_builder.py", line 73, in post
    return await self.request_adapter.send_no_response_content_async(request_info, error_mapping)
  File "/home/demouser/.local/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py", line 377, in send_no_response_content_async
    await self.throw_failed_responses(response, error_map, parent_span, parent_span)
  File "/home/demouser/.local/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py", line 501, in throw_failed_responses
    raise exc
msgraph.generated.models.o_data_errors.o_data_error.ODataError:
        APIError
        Code: 400
        message: None
        error: MainError(additional_data={}, code='Request_BadRequest', details=None, inner_error=InnerError(additional_data={'date': DateTime(2023, 12, 29, 13, 33, 31, tzinfo=Timezone('UTC'))}, client_request_id='...', date=None, odata_type=None, request_id='3174d15a-5101-49ab-acbf-555bff34922f'), message='Unexpected segment DynamicPathSegment. Expected property/$value.', target=None)   


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py", line 107, in <module>
    _ansiballz_main()
  File "/home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', _modlib_path=modlib_path),
  File "/usr/lib64/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 501, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 497, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 249, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 446, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py", line 307, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 479, in fail
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py", line 1541, in fail_json
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py", line 1514, in _return_formatted
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py", line 927, in remove_values
  File "/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py", line 470, in _remove_values_conditionsTypeError: Value of unknown type: <class 'msgraph.generated.models.o_data_errors.o_data_error.ODataError'>,
        APIError
        Code: 400
        message: None
        error: MainError(additional_data={}, code='Request_BadRequest', details=None, inner_error=InnerError(additional_data={'date': DateTime(2023, 12, 29, 13, 33, 31, tzinfo=Timezone('UTC'))}, client_request_id='...', date=None, odata_type=None, request_id='3174d15a-5101-49ab-acbf-555bff34922f'), message='Unexpected segment DynamicPathSegment. Expected property/$value.', target=None)   

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 302, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 324, in update_members\n  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 647, in run_until_complete\n    return future.result()\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 472, in add_group_member\n  File \"/home/demouser/.local/lib/python3.9/site-packages/msgraph/generated/groups/item/members/ref/ref_request_builder.py\", line 73, in post\n    return await self.request_adapter.send_no_response_content_async(request_info, error_mapping)\n  File \"/home/demouser/.local/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py\", line 377, in send_no_response_content_async\n    await self.throw_failed_responses(response, error_map, parent_span, parent_span)\n  File \"/home/demouser/.local/lib/python3.9/site-packages/kiota_http/httpx_request_adapter.py\", line 501, in throw_failed_responses\n    raise exc\nmsgraph.generated.models.o_data_errors.o_data_error.ODataError: \n        APIError\n        Code: 400\n        message: None\n        error: MainError(additional_data={}, code='Request_BadRequest', details=None, inner_error=InnerError(additional_data={'date': DateTime(2023, 12, 29, 13, 33, 31, tzinfo=Timezone('UTC'))}, client_request_id='...', date=None, odata_type=None, request_id='3174d15a-5101-49ab-acbf-555bff34922f'), message='Unexpected segment DynamicPathSegment. Expected property/$value.', target=None)\n        \n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/demouser/.ansible/tmp/ansible-tmp-1703856792.0072005-8573-3056020557212/AnsiballZ_azure_rm_adgroup.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_adgroup', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 501, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 497, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 249, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 446, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_adgroup.py\", line 307, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 479, in fail\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py\", line 1541, in fail_json\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/basic.py\", line 1514, in _return_formatted\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py\", line 927, in remove_values\n  File \"/tmp/ansible_azure.azcollection.azure_rm_adgroup_payload_5_8av5hl/ansible_azure.azcollection.azure_rm_adgroup_payload.zip/ansible/module_utils/common/parameters.py\", line 470, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'msgraph.generated.models.o_data_errors.o_data_error.ODataError'>, \n        APIError\n        Code: 400\n        message: None\n        error: MainError(additional_data={}, code='Request_BadRequest', details=None, inner_error=InnerError(additional_data={'date': DateTime(2023, 12, 29, 13, 33, 31, tzinfo=Timezone('UTC'))}, client_request_id='...', date=None, odata_type=None, request_id='3174d15a-5101-49ab-acbf-555bff34922f'), message='Unexpected segment DynamicPathSegment. Expected property/$value.', target=None)\n        \n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by p3ck** [comment]
Hello,

I was able to reproduce this with the built in Integration tests here:
https://github.com/ansible-collections/azure/blob/dev/tests/integration/targets/azure_rm_adgroup/tasks/main.yml#L63

But when I looked at the azure client documentation I only found you can add members via the object id.

https://learn.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#az-ad-group-member-add

So I changed the tests playbook to use the object_id and it works as expected.

Can someone who has more experience with Azure tell me if we simply need to update the examples and test code?  I am very new to Azure so I could be misunderstanding something here.

**Comment by rooso** [comment]
> Hello,
> 
> I was able to reproduce this with the built in Integration tests here: https://github.com/ansible-collections/azure/blob/dev/tests/integration/targets/azure_rm_adgroup/tasks/main.yml#L63
> 
> But when I looked at the azure client documentation I only found you can add members via the object id.
> 
> https://learn.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#az-ad-group-member-add
> 
> So I changed the tests playbook to use the object_id and it works as expected.
> 
> Can someone who has more experience with Azure tell me if we simply need to update the examples and test code? I am very new to Azure so I could be misunderstanding something here.

Hi and thanks for the update! Could you post an example what you have changed? In the test playbooks (https://github.com/ansible-collections/azure/blob/dev/tests/integration/targets/azure_rm_adgroup/tasks/main.yml#L63) and in my example all the users are added by the object id, aren't they?

**Comment by p3ck** [comment]
> > Hello,
> > I was able to reproduce this with the built in Integration tests here: https://github.com/ansible-collections/azure/blob/dev/tests/integration/targets/azure_rm_adgroup/tasks/main.yml#L63
> > But when I looked at the azure client documentation I only found you can add members via the object id.
> > https://learn.microsoft.com/en-us/cli/azure/ad/group/member?view=azure-cli-latest#az-ad-group-member-add
> > So I changed the tests playbook to use the object_id and it works as expected.
> > Can someone who has more experience with Azure tell me if we simply need to update the examples and test code? I am very new to Azure so I could be misunderstanding something here.
> 
> Hi and thanks for the update! Could you post an example what you have changed? In the test playbooks (https://github.com/ansible-collections/azure/blob/dev/tests/integration/targets/azure_rm_adgroup/tasks/main.yml#L63) and in my example all the users are added by the object id, aren't they?

Hi!

I went ahead and created a Pull Request with my changes.  

Thanks!
