### ISSUE TITLE
azure_rm_gallery and azure_rm_gallery_info crashing on KeyError: 'description'

### ISSUE THREAD

**Issue by markstoel** [ansible/ansible_collections_azure#1473]
##### SUMMARY

When I try to get info or create a shared image gallery I get and error stating KeyError: 'description'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_gallery_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.2]
  config file = /home/marks/projects/voyager/ansible.cfg
  configured module search path = ['/home/marks/projects/voyager/library', '/home/marks/projects/requirements_roles/common/library', '/home/marks/projects/voyager/roles/common/library']
  ansible python module location = /home/marks/.pyenv/versions/3.11.7/envs/voyager/lib/python3.11/site-packages/ansible
  ansible collection location = /home/marks/projects/voyager/collections:/home/marks/projects/requirements_collections:/usr/share/ansible/collections/ansible_collections
  executable location = /home/marks/.pyenv/versions/3.11.7/envs/voyager/bin/ansible
  python version = 3.11.7 (main, Dec 14 2023, 11:09:56) [GCC 11.4.0] (/home/marks/.pyenv/versions/3.11.7/envs/voyager/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/marks/.pyenv/versions/3.11.7/envs/voyager/lib/python3.11/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.19.0 

# /home/marks/projects/voyager/collections/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 2.2.0  
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/marks/projects/voyager/ansible.cfg) = True
CALLBACKS_ENABLED(/home/marks/projects/voyager/ansible.cfg) = ['profile_tasks', 'voyager.awx.voyager']
COLLECTIONS_PATHS(/home/marks/projects/voyager/ansible.cfg) = ['/home/marks/projects/voyager/collections', '/home/marks/projects/requirements_collectio>
CONFIG_FILE() = /home/marks/projects/voyager/ansible.cfg
DEFAULT_FILTER_PLUGIN_PATH(/home/marks/projects/voyager/ansible.cfg) = ['/home/marks/projects/voyager/plugins/filter_plugins']
DEFAULT_FORKS(/home/marks/projects/voyager/ansible.cfg) = 25
DEFAULT_GATHERING(/home/marks/projects/voyager/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/marks/projects/voyager/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/marks/projects/voyager/ansible.cfg) = ['/home/marks/projects/voyager/inventories/local/hosts']
DEFAULT_INTERNAL_POLL_INTERVAL(/home/marks/projects/voyager/ansible.cfg) = 0.001
DEFAULT_LOOKUP_PLUGIN_PATH(/home/marks/projects/voyager/ansible.cfg) = ['/home/marks/projects/voyager/plugins/lookup']
DEFAULT_MANAGED_STR(/home/marks/projects/voyager/ansible.cfg) = This file is managed by Ansible.%n
template: {file}
date: %Y-%m-%d %H:%M:%S
user: {uid}
host: {host}
DEFAULT_MODULE_PATH(/home/marks/projects/voyager/ansible.cfg) = ['/home/marks/projects/voyager/library', '/home/marks/projects/requirements_roles/commo>
DEFAULT_MODULE_UTILS_PATH(/home/marks/projects/voyager/ansible.cfg) = ['/home/marks/projects/voyager/library/module_utils', '/home/marks/projects/requi>
DEFAULT_POLL_INTERVAL(/home/marks/projects/voyager/ansible.cfg) = 5
DEFAULT_ROLES_PATH(/home/marks/projects/voyager/ansible.cfg) = ['/home/marks/projects/voyager/roles', '/home/marks/projects/requirements_roles']
DEFAULT_STDOUT_CALLBACK(/home/marks/projects/voyager/ansible.cfg) = default
DEFAULT_TIMEOUT(/home/marks/projects/voyager/ansible.cfg) = 30
DEFAULT_TRANSPORT(/home/marks/projects/voyager/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/marks/.voyager.txt
HOST_KEY_CHECKING(/home/marks/projects/voyager/ansible.cfg) = False
INTERPRETER_PYTHON(/home/marks/projects/voyager/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/marks/projects/voyager/ansible.cfg) = False
TRANSFORM_INVALID_GROUP_CHARS(/home/marks/projects/voyager/ansible.cfg) = always
```

##### OS / ENVIRONMENT

I'm running Ubuntu 22.04, but it is also failing on our AKS cluster (latest stable version)

##### STEPS TO REPRODUCE

See test example below

```yaml
---
- name: Test of gallery exists
  hosts: localhost
  tasks:
    - name: Get info about the shared image gallery
      azure.azcollection.azure_rm_gallery_info:
        resource_group: myResourceGroup
        name: whatever_existing_or_non_exising_gallery
      register: gallery_info

    - name: Debug info 
      debug:
        var: gallery_info

```

##### EXPECTED RESULTS

I'd expect to get the gallery info 

##### ACTUAL RESULTS

```paste below
It crashes with the following error message:

The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 47, in invoke_module
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py", line 250, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py", line 246, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py", line 123, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 469, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py", line 135, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py", line 174, in get
  File "/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py", line 235, in format_item
KeyError: 'id'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py\", line 250, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py\", line 246, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py\", line 123, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 469, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py\", line 135, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py\", line 174, in get\n  File \"/tmp/ansible_azure.azcollection.azure_rm_gallery_info_payload_y_6as1f2/ansible_azure.azcollection.azure_rm_gallery_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_gallery_info.py\", line 235, in format_item\nKeyError: 'id'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by Fred-sun** [comment]
Fixes by #1483

**Comment by markstoel** [comment]
The same also occurs in azure.azcollection.azure_rm_gallery. Not sure if that was clear as it was only stated in the title..

**Comment by Fred-sun** [comment]
@markstoel Yes, the two modules handle the return value differently. azure_rm_gallery.py directly returns the value json sequence, only if the return value is not None will be obtained through the dictionary. So no need to change azure_rm_gallery.py. Thank you!
