### ISSUE TITLE
ContainerServiceClient NotImplementedError: APIVersion 2019-04-01 is not available 

### ISSUE THREAD

**Issue by boraozkan** [ansible/ansible_collections_azure#163]
##### SUMMARY

My ansible task is for creating aks and I use this yaml but it failed with API version is not available

```
---
  - name: Create a managed Azure Container Services (AKS) cluster
    azure.azcollection.azure_rm_aks:
      name: "{{ aks_name }}"
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
      dns_prefix: "{{ aks_name }}"
      kubernetes_version: "{{aks_version}}"
      linux_profile:
        admin_username: "{{ username }}"
        ssh_key: "{{ ssh_key }}"
      service_principal:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      agent_pool_profiles:
        - name: default
          count: 4
          vm_size: Standard_D2_v2
      tags:
        Environment: Production
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ContainerServiceClient

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Apr 16 2020, 17:47:17) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```paste below
nothing changed
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

I was expected to execute a running aks 

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1592222047.7012603-670-9274464576862/AnsiballZ_azure_rm_aks.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1592222047.7012603-670-9274464576862/AnsiballZ_azure_rm_aks.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1592222047.7012603-670-9274464576862/AnsiballZ_azure_rm_aks.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_aks', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.5/runpy.py", line 196, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py", line 921, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py", line 917, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py", line 587, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 418, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py", line 603, in exec_module
  File "/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py", line 831, in get_aks
  File "/usr/local/lib/python3.5/dist-packages/azure/mgmt/containerservice/container_service_client.py", line 152, in managed_clusters
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-04-01 is not available
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1592222047.7012603-670-9274464576862/AnsiballZ_azure_rm_aks.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1592222047.7012603-670-9274464576862/AnsiballZ_azure_rm_aks.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1592222047.7012603-670-9274464576862/AnsiballZ_azure_rm_aks.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_aks', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.5/runpy.py\", line 196, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.5/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 921, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 917, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 587, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 418, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 603, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_aks_payload_8w3tunib/ansible_azure.azcollection.azure_rm_aks_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_aks.py\", line 831, in get_aks\n  File \"/usr/local/lib/python3.5/dist-packages/azure/mgmt/containerservice/container_service_client.py\", line 152, in managed_clusters\n    raise NotImplementedError(\"APIVersion {} is not available\".format(api_version))\nNotImplementedError: APIVersion 2019-04-01 is not available\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

```paste below
File "/usr/local/lib/python3.5/dist-packages/azure/mgmt/containerservice/container_service_client.py", line 152, in managed_clusters
    raise NotImplementedError("APIVersion {} is not available".format(api_version))
NotImplementedError: APIVersion 2019-04-01 is not available
```

**Comment by boraozkan** [comment]
here is fix my problem in `/root/.ansible/collections/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py `

```
    @property
    def containerservice_client(self):
        self.log('Getting container service client')
        if not self._containerservice_client:
            self._containerservice_client = self.get_mgmt_svc_client(ContainerServiceClient,
                                                                     base_url=self._cloud_environment.endpoints.resource_manager,
                                                                     api_version='2017-07-01')
        return self._containerservice_client

    @property
    def managedcluster_models(self):
        self.log("Getting container service models")
        return ContainerServiceClient.models('2019-04-01')

    @property
    def managedcluster_client(self):
        self.log('Getting container service client')
        if not self._managedcluster_client:
            self._managedcluster_client = self.get_mgmt_svc_client(ContainerServiceClient,
                                                                   base_url=self._cloud_environment.endpoints.resource_manager,
                                                                   api_version='2018-03-31')
        return self._managedcluster_client
```

**Comment by dougalII** [comment]
issue still persists on version:
ansible 2.11.0.dev0

performed the same fix but also had to update the `def managedcluster_models(self):` to return '2017-07-01'
