### ISSUE TITLE
`azure_keyvault_secret` lookup might be broken

### ISSUE THREAD

**Issue by pat-s** [ansible/ansible_collections_azure#1777]
##### SUMMARY

`lookup('azure.azcollection.azure_keyvault_secret'` doesn't seem to work, no matter the auth method.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.1]
```

##### COLLECTION VERSION

```paste below
3.1.0
```

##### STEPS TO REPRODUCE

Tried to authenticate via `az login`, via explicit credentials (`client_id`, `secret`, tenant_id`) or env vars. All fail. Each of them with slighltly different methods

```yaml
lookup('azure.azcollection.azure_keyvault_secret', 'secret', vault_url='<vault url>')

lookup('azure.azcollection.azure_keyvault_secret', 'secret', client_id='<client_id>',tenant_id='<tenant_id>',secret='<secret>',vault_url='<vault url>')
```

Yes, I can query secrets in the respective key vault and the credentials are correct. 
I am Key vault admin and the credentials are used in other automation workflows.

##### EXPECTED RESULTS

Authentication works and secrets are returned.

##### ACTUAL RESULTS

```paste below
# env var auth
FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'NameError'>, original message: name 'DefaultAzureCredential' is not defined. name 'DefaultAzureCredential' is not defined"}

# keyword auth
FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'NameError'>, original message: name 'ClientSecretCredential' is not defined. name 'ClientSecretCredential' is not defined"}
```

**Comment by kandrew5** [comment]
I facing the same problem

EDIT:
It was related to the python version I has installed. Once I changed to a supported one, it worked

**Comment by olljanat** [comment]
FYI, I ended up to this issue because having two versions of `azure.azcollection` installed and had installed requirements from old one. 

You can easily check if that is the case in your environment with command `ansible-galaxy collection list`

**Comment by dkettman** [comment]
I have ensured that I do not have multiple versions of the `azure.azcollection` package installed. I can run all other Azure-based modules (creating resource groups, vms, etc), but reading from the vault is causing issues.

I have tried this debug module output:
```yaml
tasks:
    - debug:
        msg: "{{ lookup('azure.azcollection.azure_keyvault_secret', 'SECRET-NAME', vault_url='https://VAULTURL.vault.azure.net/') }}"
```

The message I get back with 4 `-v`'s (sanitized for your pleasure):
```
TASK [debug] ************************************************************************************************************************************************************************************************************************************
task path: /export/repos/cs_azure_labs/playbooks/secret_server.yaml:27
Loading collection azure.azcollection from /export/repos/cs_azure_labs/lib/python3.12/site-packages/ansible_collections/azure/azcollection
exception during Jinja2 execution: Traceback (most recent call last):
  File "/export/repos/cs_azure_labs/lib/python3.12/site-packages/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 212, in run
    ret.append(secret_res.json()["value"])
               ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/repos/cs_azure_labs/lib/python3.12/site-packages/ansible/template/__init__.py", line 824, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/repos/cs_azure_labs/lib/python3.12/site-packages/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 214, in run
    raise AnsibleError('Failed to fetch secret ' + term + '.')
ansible.errors.AnsibleError: Failed to fetch secret SECRET-NAME.
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to fetch secret SECRET-NAME.. Failed to fetch secret SECRET-NAME."
}
```

**Comment by pat-s** [comment]
So, what are the problematic downstream dependencies then which need to be updated? Didn't have a change yet to test again but will do again soonish.

**Comment by Fred-sun** [comment]
@pat-s @olljanat According to the error, the 'DefaultAzureCredential' and 'ClientSecretCredential' was not imported successfully, Can you check whether ‘azure-identity'’ is installed in your environment? Thank you very much!

**Comment by misterpoulet** [comment]
I also hit this problem, and I think there's something wrong with how `TOKEN_ACQUIRED` is set.

I'm using a service principle, not MSI, and yet the lookup insists on using MSI authentication.

```
PLAY [test_az_keyvault] ********************************************************
Friday 10 January 2025  19:20:57 +0000 (0:00:00.020)       0:00:00.020 ******** 
exception during Jinja2 execution: Traceback (most recent call last):
  File "/usr/share/ansible/collections/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 212, in run
    ret.append(secret_res.json()["value"])
KeyError: 'value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ansible/template/__init__.py", line 865, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/usr/share/ansible/collections/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 214, in run
    raise AnsibleError('Failed to fetch secret ' + term + '.')
ansible.errors.AnsibleError: Failed to fetch secret mykey-key1.

TASK [Displaying the result of the keyvault_keys] ******************************
task path: /etc/ansible/tooling-ansible/test_az_keyvault.yml:23
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Failed to fetch secret mykey-key1.. Failed to fetch secret mykey-key1."
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
Friday 10 January 2025  19:20:58 +0000 (0:00:00.812)       0:00:00.832 ******** 
=============================================================================== 
Displaying the result of the keyvault_keys ------------------------------ 0.81s
```

I was able to solve this problem by specifying `use_msi=false`

**Comment by Fred-sun** [comment]
@pat-s Do your problems still exist? Whether the test has installed `azure-identity` (azcollection/requirements.txt)? Thank you!

**Comment by pat-s** [comment]
I'll have a look soon and will report back what I found. Thanks already to everyone participating here so far.

**Comment by Ratanavery** [comment]
facing this issue with msi at this point in time...

is this something intermittent as I remember the same error last week but later vanished but now again facing the same issue!!!

**Comment by Fred-sun** [comment]
@Ratanavery @misterpoulet Judging from your error and my process of reproducing the problem, it is not a bug。 You need to add access policy to your MSI VM.  You can refer to connect (https://learn.microsoft.com/en-us/azure/key-vault/general/assign-access-policy?tabs=azure-portal), thank you. 
```e.g.
 The following information is displayed for adding an access policy:
ok: [localhost] => {
    "ansible_facts": {
        "object_id": "mysecret"
    },
    "changed": false
}

**Comment by Fred-sun** [comment]
kindly ping

**Comment by Ratanavery** [comment]
Hi, I am using the rbac model for the key vault access to the ansible node MI.

**Comment by Fred-sun** [comment]
@pat-s Does this problem of yours still exist? Thank you!

**Comment by Fred-sun** [comment]
@pat-s Because of the changes in the dependent file, we made some minor modifications to it. If you are using MSI Authentication, please set use_msi=True. If you are using az login, please set use_cli=True. You can also configure client_id, tenant_id and secret in the playbook. Thank you!

**Comment by emerconn** [comment]
I am also facing the same error. I tried setting both explicit credentials in the task, as well as with env vars. I ensured that all python dependencies are installed from azcollection/requirements.txt. I tried manually installing `azure-identity` as well.

```bash
❯ ansible-playbook playbooks/windows-webserver.yml -t ssl-certs

TASK [windows/webserver : Fetch secret from Azure Key Vault] ***********************************************************
task path: /home/emerconn/workspace/dev.azure.com/nx-core-ansible/roles/windows/webserver/tasks/ssl-certs.yml:2
exception during Jinja2 execution: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 824, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emerconn/.ansible/collections/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 224, in run
    return lookup_secret_non_msi(terms, vault_url, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emerconn/.ansible/collections/ansible_collections/azure/azcollection/plugins/lookup/azure_keyvault_secret.py", line 161, in lookup_secret_non_msi
    credential = DefaultAzureCredential()
                 ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'DefaultAzureCredential' is not defined
fatal: [ansibletest02 -> localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'NameError'>, original message: name 'DefaultAzureCredential' is not defined. name 'DefaultAzureCredential' is not defined"
}
```

**Comment by emerconn** [comment]
I also get this error when attempting to use CLI creds:

```
fatal: [ansibletest02 -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'azure.azcollection.azure_keyvault_secret'. Error was a <class 'NameError'>, original message: name 'ClientSecretCredential' is not defined. name 'ClientSecretCredential' is not defined"}
```

**Comment by pat-s** [comment]
@Fred-sun I now tried it again (sorry for the long silence!) and it turned out that both `azure-keyvault-secrets` and `azure-identity` (pip) were needed to make it work with v3.3.1.

FYI: This package is not listed as a requirement on the [help page](https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_keyvault_secret_lookup.html#ansible-collections-azure-azcollection-azure-keyvault-secret-lookup-requirements).

**Comment by emerconn** [comment]
My problem was installing ansible-core via apt. After removing the apt install and installing via pip within a venv, it works fine.

Is this expected?

**Comment by Fred-sun** [comment]
@emerconn @pat-s The pip is the python package manager and is at the python interpreter level. apt-get is the package manager of ubuntu and is at the system disease level. There may be differences in the software versions installed by the two. So for better flexibility. It is recommended that you install it using pip. Thank you!

**Comment by Fred-sun** [comment]
> I now tried it again (sorry for the long silence!) and it turned out that both `azure-keyvault-secrets` and `azure-identity` (pip) were needed to make it work with v3.3.1.
> 
> FYI: This package is not listed as a requirement on the

@pat-s In the requirement file, When installed azure-keyvault==4.2.0, the azure-keyvault-secret and azure-keyvault-key will install at same time. Thank you!

**Comment by pat-s** [comment]
@Fred-sun Thanks. Yet, will `azure-keyvault` be mentioned as a local dep in the next release?

**Comment by Fred-sun** [comment]
@pat-s I don't understand what you mean. ‘azure-keyvault==4.2.0’ has been installed in requiements.txt. Thank you!
https://github.com/ansible-collections/azure/blob/d675c5337e9f253fafed355f9d91e9ef7d45276a/requirements.txt#L40

**Comment by pat-s** [comment]
https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_keyvault_secret_lookup.html#ansible-collections-azure-azcollection-azure-keyvault-secret-lookup-requirements does not mention `azure-keyvault` being a local dependency on the controller node.

It only says `requests` and `azure` are required. If `azure` includes `azure-keyvault` -> fine, though I'd argue that listing `azure-keyvault` there instead of `azure` (which is probably a larger package containing more sub-packages) would be more precise.

**Comment by Fred-sun** [comment]
Yes, but coming back to your question, from your error report, it can be seen that the two modules' 'ClientSecretCredential' and 'DefaultAzureCredential' were not found. And both of these are in the package azure -identity.  Could you take a try (pip3 list |grep 'azure-identity'). Thanks

**Comment by pat-s** [comment]
I am confused 😄 I already said that my issue was solved [in this comment](https://github.com/ansible-collections/azure/issues/1777#issuecomment-2864133011). 

To make it clear: yes, installing `azure-identity` via pip on the controller host helped.

**Comment by Fred-sun** [comment]
I'm very sorry. I ignored the comments above.
