### ISSUE TITLE
azure_rm_virtualmachine fails when VM is stopped. 

### ISSUE THREAD

**Issue by mrwalters1988** [ansible/ansible_collections_azure#238]
##### SUMMARY

A 'keyerror' appears referencing 'DiskSizeGB when the VM is stopped and the plugin is run. 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine 
##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting
ANSIBLE_PIPELINING(/home/vagrant/.ansible.cfg) = True
DEFAULT_LOG_PATH(/home/vagrant/.ansible.cfg) = /var/log/ansible.log
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/vagrant/.ansible/.vault_password
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(/home/vagrant/.ansible.cfg) = False
```

##### STEPS TO REPRODUCE

Deploy a Windows virtual machine. Shut down the VM. Then run the same code a second time. 

```yaml
- name: Create VM 
  azure_rm_virtualmachine:
    resource_group: testrg
    name: testvm10
    admin_username: winusername
    admin_password: <your password here>
    image:
      offer: MicrosoftWindowsServer
      publisher: WindowsServer
      sku: 2016-Datacenter
      version: latest

```

##### EXPECTED RESULTS

The task would execute any changes in the config, or skip if none is needed. 

##### ACTUAL RESULTS

```paste below
2020-08-21T16:03:28.9763973Z [0;31m  File "/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 2202, in <module>[0m
2020-08-21T16:03:28.9765111Z [0;31m  File "/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 2198, in main[0m
2020-08-21T16:03:28.9766326Z [0;31m  File "/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 901, in __init__[0m
2020-08-21T16:03:28.9767432Z [0;31m  File "/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 348, in __init__[0m
2020-08-21T16:03:28.9768570Z [0;31m  File "/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 1574, in exec_module[0m
2020-08-21T16:03:28.9769271Z [0;31mKeyError: 'diskSizeGB'[0m
2020-08-21T16:03:28.9769728Z [0;31mfatal: [azure]: FAILED! => {[0m
2020-08-21T16:03:28.9770178Z [0;31m    "changed": false,[0m
2020-08-21T16:03:28.9776547Z [0;31m    "module_stderr": "Traceback (most recent call last):\n  File \"/home/vsts_azpcontainer/.ansible/tmp/ansible-tmp-1598025807.0454414-611-94663843324888/AnsiballZ_azure_rm_virtualmachine.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/vsts_azpcontainer/.ansible/tmp/ansible-tmp-1598025807.0454414-611-94663843324888/AnsiballZ_azure_rm_virtualmachine.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vsts_azpcontainer/.ansible/tmp/ansible-tmp-1598025807.0454414-611-94663843324888/AnsiballZ_azure_rm_virtualmachine.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_virtualmachine', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 2202, in <module>\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 2198, in main\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 901, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py\", line 348, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 1574, in exec_module\nKeyError: 'diskSizeGB'\n",[0m
2020-08-21T16:03:28.9780819Z [0;31m    "module_stdout": "",[0m
2020-08-21T16:03:28.9781390Z [0;31m    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",[0m
2020-08-21T16:03:28.9781887Z [0;31m    "rc": 1[0m
2020-08-21T16:03:28.9782242Z [0;31m}[0m
2020-08-21T16:03:28.9790513Z 
2020-08-21T16:03:28.9790885Z PLAY RECAP *********************************************************************
2020-08-21T16:03:28.9791901Z [0;31mazure[0m                      : [0;32mok=58  [0m [0;33mchanged=3   [0m unreachable=0    [0;31mfailed=1   [0m [0;36mskipped=28  [0m rescued=0    ignored=0   
2020-08-21T16:03:28.9792504Z 
2020-08-21T16:03:29.0600256Z 
2020-08-21T16:03:29.0674115Z ##[error]Bash exited with code '2'.
```

**Comment by Fred-sun** [comment]
@mrwalters1988 Thank you for reporting this issue. What is your purpose of shutting down and running again? If the VM is shut down during the second run, because some configuration cannot be obtained in the shutdown state, it will cause an error, which is reasonable. Thank you!

**Comment by mrwalters1988** [comment]
Fred-sun, 
In order to modify the disks, the VM needs to be shut down.

**Comment by UnwashedMeme** [comment]
@mrwalters1988 is there any chance you have a slightly older version of this library?  I fixed this bug for me recently: https://github.com/ansible-collections/azure/pull/185/files

**Comment by Fred-sun** [comment]
@mrwalters1988 Do you still have this problem? I cannot assign the error you encountered in the local virtual machine. Can you share how you encountered this problem? It will helpful to resolve the issue! Thank you very much!

**Comment by UnwashedMeme** [comment]
@mrwalters1988 I think one problem you may be having is you are using the ansible 2.9 version of this module, not the one from this collection (recently fixed).

Try writing the module name with the fully qualified collection name: `azure.azcollection.azure_rm_virtualmachine`

E.g. in the stacktrace you posted:
```
2020-08-21T16:03:28.9763973Z �[0;31m  File "/tmp/ansible_azure_rm_virtualmachine_payload_4apbhnr1/ansible_azure_rm_virtualmachine_payload.zip/
<inserted newline>
ansible/modules/cloud/azure/azure_rm_virtualmachine.py", line 2202, in <module>�[0m
```
That path pattern "`ansible/modules/cloud/azure/azure_rm_virtualmachine.py`" is from https://github.com/ansible/ansible/blob/v2.9.13/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py, not from https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_virtualmachine.py.

Having been super confused recently about "why doesn't the behavior match the code" I'm trying to help spread the word :-)

**Comment by solutitfischer** [comment]
Hello everybody, 
I am having the same issue, maybe I can provide the details to get to the bottom of this. 

For me the issue comes up if I just want to start a vm that is deallocated:
`azure_rm_virtualmachine:
resource_group: "{{ resource_group_name }}"
name: "{{ vm }}"`

Error: 
`"/tmp/ansible_azure_rm_virtualmachine_payload_bh_iz0ra/ansible_azure_rm_virtualmachine_payload.zip/ansible/modules/cloud/azure/azure_rm_virtualmachine.py\", line 1574, in exec_module\nKeyError: 'diskSizeGB'\n",`

**Comment by UnwashedMeme** [comment]
@solutitfischer, please look [at my comment here](https://github.com/ansible-collections/azure/issues/238#issuecomment-688911229) and make sure you are referencing the module as `azure.azcollection.azure_rm_virtualmachine`. I think this is an issue with bad code reference invisibly using old version of the code.

**Comment by solutitfischer** [comment]
I tried using the complete reference of the module but got a syntax-error so tried it this way:
```
- name: Start Azure VM 
  hosts: localhost
  collections: 
    - azure.azcollection
  connection: local
  tasks:
    - name: Get facts by name
      azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm }}"

    - name: Start virtual machine. This might take a while...
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm }}"
```

For this I get the following error:
```
Error creating or updating virtual machine siid1 - Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'"
```

I updated everything with the following commands beforehand:
```
1. ansible-galaxy collection install azure.azcollection --force

2. sudo pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
```

**Comment by Fred-sun** [comment]
@mrwalters1988 This may be a problem in the process of your installation, it is recommended that you uninstall and reinstall. Thank you very much!
```e.g.
sudo pip3 install ansible --upgrade 
sudo rm -rf  ~/.ansible
sudo  ansible-galaxy collection install azure.azcollection --force
