### ISSUE TITLE
azure_rm_resourcegroup fails with AttributeError

### ISSUE THREAD

**Issue by jschwanz** [ansible/ansible_collections_azure#253]
##### SUMMARY
I'm trying to create a resource group. This looks similar to [Ansible issue 59096](https://github.com/ansible/ansible/issues/59096), which it appears the fix was committed after the collection code was split out from the main Ansible repository.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_resourcegroup

##### ANSIBLE VERSION

```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vsts/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]
```

##### OS / ENVIRONMENT
Azure DevOps Ubuntu 20.04 pipeline agent

##### STEPS TO REPRODUCE

```yaml
- name: Create Resource Group
  azure_rm_resourcegroup:
    name: myresourcegroup
    location: westus
    tags: "{{ rg_tags }}"
```

##### EXPECTED RESULTS

I expect a resource group to be created.

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/vsts/.ansible/tmp/ansible-tmp-1599660576.4665477-233401239077594/AnsiballZ_azure_rm_resourcegroup.py", line 102, in <module>
    _ansiballz_main()
  File "/home/vsts/.ansible/tmp/ansible-tmp-1599660576.4665477-233401239077594/AnsiballZ_azure_rm_resourcegroup.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vsts/.ansible/tmp/ansible-tmp-1599660576.4665477-233401239077594/AnsiballZ_azure_rm_resourcegroup.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_resourcegroup', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 291, in <module>
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 287, in main
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 167, in __init__
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/module_utils/azure_rm_common.py", line 348, in __init__
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 183, in exec_module
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/module_utils/azure_rm_common.py", line 881, in rm_client
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/module_utils/azure_rm_common.py", line 752, in get_mgmt_svc_client
  File "/tmp/ansible_azure_rm_resourcegroup_payload_skuk4g2n/ansible_azure_rm_resourcegroup_payload.zip/ansible/module_utils/azure_rm_common.py", line 358, in check_client_version
AttributeError: module 'azure.mgmt.resource.resources._resource_management_client' has no attribute 'VERSION'
```

**Comment by jschwanz** [comment]
Looking at this more I think there's something else going on here. I'm going to close the issue.

**Comment by stoetti** [comment]
> Looking at this more I think there's something else going on here. I'm going to close the issue.

Ran into this issue today, what exactly is going on? How to get rid of this error?

**Comment by jschwanz** [comment]
@stoetti in my case it came down to a namespace issue, where I think it was getting confused between the collection and the "built-in" Azure modules in 2.9.x. I was attempting to do the following:

```yaml
- hosts: all
  collections:
    - azure.azcollection
  tasks:
    - azure_rm_resourcegroup:
        name: foo
```

I changed to use the full namespace, and it started using the collection properly.

```yaml
- hosts: all
  tasks:
    - azure.azcollection.azure_rm_resourcegroup:
        name: foo
```

**Comment by stoetti** [comment]
Thank for the update
