### ISSUE TITLE
Uploading bigger files to storage blog reaches timeout

### ISSUE THREAD

**Issue by pun-ky** [ansible/ansible_collections_azure#474]
##### SUMMARY

```
TASK [upload resources] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: azure.common.AzureException: ('Connection aborted.', timeout('The write operation timed out'))
fatal: [local]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/Users/krystian.panek/.pyenv/versions/3.9.2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/krystian.panek/.pyenv/versions/3.9.2/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/krystian.panek/.pyenv/versions/3.9.2/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/krystian.panek/.pyenv/versions/3.9.2/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/krystian.panek/.pyenv/versions/3.9.2/lib/python3.9/http/client
```

looks like this:
https://github.com/Azure/azure-storage-python/issues/228#issuecomment-308372215
however: 

```
Name: azure-storage
Version: 0.35.1
Summary: Microsoft Azure Storage Client Library for Python
Home-page: https://github.com/Azure/azure-storage-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: Apache License 2.0
Location: /Users/krystian.panek/.pyenv/versions/3.9.2/lib/python3.9/site-packages
Requires: azure-common, requests, python-dateutil, cryptography, azure-nspkg
Required-by: 
```

looks like even the version after the patch is not working. any suggestions?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module fails after few minutes and only few smaller files are uploaded

```
- hosts: local
  gather_facts: no
  tasks:
    - name: upload resources
      azure.azcollection.azure_rm_storageblob:
        resource_group: "{{ az_resource_group_common }}"
        storage_account_name: "{{ az_storage_account_common }}"
        container: "{{ az_storage_container_resources }}"
        batch_upload_dst: "/"
        batch_upload_src: "{{ controller_resource_dir }}"
```

##### ANSIBLE VERSION

```paste below
ansible 2.10.7
  config file = None
  configured module search path = ['/Users/krystian.panek/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/krystian.panek/.pyenv/versions/3.9.2/lib/python3.9/site-packages/ansible
  executable location = /Users/krystian.panek/.pyenv/versions/3.9.2/bin/ansible
  python version = 3.9.2 (default, Mar 29 2021, 09:49:19) [Clang 11.0.3 (clang-1103.0.32.62)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Mac, Sierra

##### EXPECTED RESULTS

* provide configurable timeout option
* increase timeout 

##### ACTUAL RESULTS

no way to avoid timeout (?)

**Comment by zunyangc** [comment]
Closing this issue as fixed. Refer #2133. 

Feel free to reopen if similar issues encountered. Thanks!
