### ISSUE TITLE
Unable to delete managed disk using azure.azcollection.azure_rm_manageddisk

### ISSUE THREAD

**Issue by rcdlinux** [ansible/ansible_collections_azure#541]
Error when trying to remove managed disk from Azure VM using Azure certified collection via Ansible playbook on Ansible Tower. From Azure Painel or CLI the disk is removed with success, the error is happening only via Ansible.
Below the complete playbook to test followed by the error returned from Azure:

```
## -- Playbook to manage Azure disk
## --- cut ---

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Bloco add disk azure
    block:

    - set_fact:
        hostname_azure: "{{ hostname.split('.')[0] | lower }}"
       
    - name: Get VM Availability Zone
      azure_rm_resource_facts:
        resource_group: "{{ resource_group }}"
        resource_name: "{{ hostname_azure }}"
        resource_type: VirtualMachines
        provider: Compute
      register: result

    - set_fact:
        zone: "{{ result.response[0].zones | list | first  }}"
      when: result.response[0].zones is defined

    # Validação do Resource Group e Hostname
    - debug:
        msg: "AWX:DATA:ALERT: Resource Group ou Hostname não encontrado!!!"
      when: resource_group is not defined
    - meta: end_play   
      when: resource_group is not defined

    # Cria e attach o disco na VM
    - name: Create and attach disk to VM
      azure_rm_manageddisk:
        name: "{{ disk_name }}"
        location: "{{ location | default('brazilsouth') }}"
        resource_group: "{{ resource_group }}"
        disk_size_gb: "{{ disk_size }}"
        managed_by: "{{ hostname_azure }}"
        storage_account_type: "{{ storage_account_type | default('Standard_LRS') }}"
        attach_caching: read_only
        zone: "{{ zone | default(omit) }}"
      register: dfrootDISK
      ignore_errors: no

    - set_stats:
        data:
          msg_result_stats: "AWX:SUCCESS: Disco adicionado com sucesso!"

    - set_fact:
        msg_result: "AWX:SUCCESS: Disco adicionado com sucesso!"
     
    - debug:
        msg:
        - "AWX:DATA:STATUS: {{ dfrootDISK.changed }}"
        - "{{ msg_result }}"

# --------------------------------------------------     
    rescue:
# --------------------------------------------------

    - name: Unmount the managed disk to VM
      azure_rm_manageddisk:
        name: "{{ disk_name }}"
        location: "{{ location | default('brazilsouth') }}"
        resource_group: "{{ resource_group }}"
        disk_size_gb: "{{ disk_size }}"

    - name: Get facts for all managed disks managed by a specific vm
      azure_rm_manageddisk_info:
        name: "{{ disk_name }}"
        resource_group: "{{ resource_group }}"

    - name: resource info
      azure_rm_resource_info:
        resource_group: "{{ resource_group }}"
        provider: "Compute"
        resource_type: "disks"
        resource_name: "{{ disk_name }}"
      register: output2

    # deletar e deattach o disco na VM
    - name: Delete and deattach disk to VM
      azure_rm_manageddisk:
        name: "{{ disk_name }}"
        location: "{{ location | default('brazilsouth') }}"
        resource_group: "{{ resource_group }}"
        state: absent
      register: dfrootDISK
      ignore_errors: yes

    - set_stats:
        data:
          msg_result_stats: "AWX:ERROR: Error ao adicionar o disco!"
         
    - set_fact:
        msg_result: "AWX:ERROR: Error ao adicionar o disco!"
 
    - fail:
        msg: "{{ msg_result }}"

#  --- cut ---
# End of playbook
```

*** Error from Ansible Tower certified Azure Collection - Subscription, server names and resources are redacted .

```
=====================================================================================
TASK [Delete and deattach disk to VM] **
task path: /tmp/awx_1450238_wdfpz5f3/project/add_disk.yml:73
Using module file /tmp/awx_1450238_wdfpz5f3/project/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c '/var/lib/awx/venv/ansible3/bin/python && sleep 0'
The full traceback is:
WARNING: The below traceback may not be related to the actual failure.
  File "/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_wLusWS/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 463, in delete_managed_disk
  File "/var/lib/awx/venv/ansible3/lib/python2.7/site-packages/azure/mgmt/compute/v2019_07_01/operations/_disks_operations.py", line 385, in delete
    **operation_config
  File "/var/lib/awx/venv/ansible3/lib/python2.7/site-packages/azure/mgmt/compute/v2019_07_01/operations/_disks_operations.py", line 352, in _delete_initial
    raise exp
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "ad_user": null, 
            "adfs_authority_url": null, 
            "api_profile": "latest", 
            "append_tags": true, 
            "attach_caching": null, 
            "auth_source": "auto", 
            "cert_validation_mode": null, 
            "client_id": null, 
            "cloud_environment": "AzureCloud", 
            "create_option": null, 
            "disk_size_gb": null, 
            "location": "brazilsouth", 
            "lun": null, 
            "managed_by": null, 
            "name": "server-00000-000000-001-dsk01", 
            "os_type": null, 
            "password": null, 
            "profile": null, 
            "resource_group": "REDACTED0000000000000001", 
            "secret": null, 
            "source_uri": null, 
            "state": "absent", 
            "storage_account_type": null, 
            "subscription_id": null, 
            "tags": null, 
            "tenant": null, 
            "zone": null
        }
    }, 
    "msg": "Error deleting the managed disk: Azure Error: OperationNotAllowed\nMessage: Disk 'server-00000-000000-001-dsk01' is being attached to VM '/subscriptions/redacted-0000-0000-0000-000000000001/resourceGroups/REDACTED0000000000000001/providers/Microsoft.Compute/virtualMachines/server-00000-000000-001', therefore operation is not allowed"
}
=====================================================================================
```

*** Ansible Tower Job error output:

```
=====================================================================================

GET /api/v2/jobs/1447077/stdout/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: text/plain ;utf-8
Vary: Accept
X-API-Node: tower01
X-API-Product-Name: Red Hat Ansible Tower
X-API-Product-Version: 3.8.1
X-API-Query-Count: 0
X-API-Query-Time: 0.000s
X-API-Time: 0.048s

ansible-playbook 2.9.15
  config file = /tmp/awx_1447077_awxjs_pa/project/ansible.cfg
  configured module search path = [u'/var/lib/awx/projects/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Using /tmp/awx_1447077_awxjs_pa/project/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/awx_1447077_awxjs_pa/tmp3tpjvbip as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /tmp/awx_1447077_awxjs_pa/tmp3tpjvbip inventory source with script plugin
Loading callback plugin awx_display of type stdout, v2.0 from /var/lib/awx/venv/awx/lib/python3.6/site-packages/ansible_runner/callbacks/awx_display.py

PLAYBOOK: add_disk.yml *****
Positional arguments: add_disk.yml
diff: True
remote_user: root
become_method: sudo
inventory: (u'/tmp/awx_1447077_awxjs_pa/tmp3tpjvbip',)
forks: 5
tags: (u'all',)
extra_vars: (u'@/tmp/awx_1447077_awxjs_pa/env/extravars',)
verbosity: 4
connection: smart
timeout: 60
1 plays in add_disk.yml

PLAY [localhost] ***
META: ran handlers

TASK [set_fact] ****
task path: /tmp/awx_1447077_awxjs_pa/project/add_disk.yml:12
ok: [localhost] => {
    "ansible_facts": {
        "hostname_azure": "server-00000-000000-001"
    }, 
    "changed": false
}

TASK [Get VM Availability Zone] ****
task path: /tmp/awx_1447077_awxjs_pa/project/add_disk.yml:15
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_resource_facts.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
[WARNING]: Azure API profile latest does not define an entry for
GenericRestClient
[DEPRECATION WARNING]: The 'azure_rm_resource_facts' module has been renamed to
 'azure_rm_resource_info'. This feature will be removed in version 2.13. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "ad_user": null, 
            "adfs_authority_url": null, 
            "api_profile": "latest", 
            "api_version": null, 
            "auth_source": null, 
            "cert_validation_mode": null, 
            "client_id": null, 
            "cloud_environment": "AzureCloud", 
            "password": null, 
            "profile": null, 
            "provider": "Compute", 
            "resource_group": "REDACTED0000000000000001", 
            "resource_name": "server-00000-000000-001", 
            "resource_type": "VirtualMachines", 
            "secret": null, 
            "subresource": [], 
            "subscription_id": null, 
            "tenant": null, 
            "url": null
        }
    }, 
    "response": [
        {
            "id": "/subscriptions/redacted-0000-0000-0000-000000000001/resourceGroups/REDACTED0000000000000001/providers/Microsoft.Compute/virtualMachines/server-00000-000000-001", 
            "location": "brazilsouth", 
            "name": "server-00000-000000-001", 
            "properties": {
                "diagnosticsProfile": {
                    "bootDiagnostics": {
                        "enabled": true, 
                        "storageUri": "https://server000000000000000000001.blob.core.windows.net/"
                    }
                }, 
                "hardwareProfile": {
                    "vmSize": "Standard_F2s_v2"
                }, 
                "networkProfile": {
                    "networkInterfaces": [
                        {
                            "id": "/subscriptions/redacted-0000-0000-0000-000000000001/resourceGroups/REDACTED0000000000000001/providers/Microsoft.Network/networkInterfaces/server-00000-000000-001-nic01", 
                            "properties": {
                                "primary": true
                            }
                        }, 
                        {
                            "id": "/subscriptions/redacted-0000-0000-0000-000000000001/resourceGroups/REDACTED0000000000000001/providers/Microsoft.Network/networkInterfaces/server-00000-000000-001-nic02", 
                            "properties": {
                                "primary": false
                            }
                        }
                    ]
                }, 
                "osProfile": {
                    "adminUsername": "ansible", 
                    "allowExtensionOperations": true, 
                    "computerName": "server-00000-000000-001", 
                    "linuxConfiguration": {
                        "disablePasswordAuthentication": false, 
                        "patchSettings": {
                            "assessmentMode": "ImageDefault", 
                            "patchMode": "ImageDefault"
                        }, 
                        "provisionVMAgent": true
                    }, 
                    "secrets": []
                }, 
                "provisioningState": "Succeeded", 
                "storageProfile": {
                    "dataDisks": [], 
                    "imageReference": {
                        "exactVersion": "0.0.4", 
                        "id": "/subscriptions/redacted-0000-0000-0000-000000000002/resourceGroups/sbrp1zb1rsgimggalglob001/providers/Microsoft.Compute/galleries/sbr000000000000000000002/images/RHEL7-Template-AZR-VRA/versions/0.0.4"
                    }, 
                    "osDisk": {
                        "caching": "ReadWrite", 
                        "createOption": "FromImage", 
                        "diskSizeGB": 127, 
                        "managedDisk": {
                            "id": "/subscriptions/redacted-0000-0000-0000-000000000001/resourceGroups/REDACTED0000000000000001/providers/Microsoft.Compute/disks/server-00000-000000-001-osd", 
                            "storageAccountType": "Standard_LRS"
                        }, 
                        "name": "server-00000-000000-001-osd", 
                        "osType": "Linux"
                    }
                }, 
                "vmId": "b210d33a-f735-485f-8546-8d1d1d3b3b1e"
            }, 
            "resources": [
                {
                    "id": "/subscriptions/redacted-0000-0000-0000-000000000001/resourceGroups/REDACTED0000000000000001/providers/Microsoft.Compute/virtualMachines/server-00000-000000-001/extensions/OmsAgentForLinux", 
                    "location": "brazilsouth", 
                    "name": "OmsAgentForLinux", 
                    "properties": {
                        "autoUpgradeMinorVersion": true, 
                        "provisioningState": "Failed", 
                        "publisher": "Microsoft.EnterpriseCloud.Monitoring", 
                        "settings": {
                            "workspaceId": "redacted-0000-0000-0000-00000000003"
                        }, 
                        "type": "OmsAgentForLinux", 
                        "typeHandlerVersion": "1.0"
                    }, 
                    "tags": {
                        "cia": "all", 
                        "cost_center": "aie", 
                        "product": "aie", 
                        "sigla": "aie"
                    }, 
                    "type": "Microsoft.Compute/virtualMachines/extensions"
                }
            ], 
            "tags": {
                "24x7": "NAO", 
                "SIGLA_OWNER": "AAA", 
                "azrbkp": "sim", 
                "cia": "all", 
                "cmdb": "SERVICOS_00000000_DE/PORTAL_JAVA_DE/PORTAL_JAVA_ARSENAL(ARS)_DE", 
                "cost_center": "aaa", 
                "demanda": "DMNDOBS0000", 
                "description": "", 
                "prj": "DMNDOBS0000", 
                "product": "aie", 
                "rpi": "5ff460ee4d77af0010000000", 
                "sigla": "ars"
            }, 
            "type": "Microsoft.Compute/virtualMachines"
        }
    ], 
    "url": "/subscriptions/redacted-0000-0000-0000-000000000001/resourceGroups/REDACTED0000000000000001/providers/Microsoft.Compute/VirtualMachines/server-00000-000000-001"
}

TASK [set_fact] ****
task path: /tmp/awx_1447077_awxjs_pa/project/add_disk.yml:23
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}

TASK [debug] ***
task path: /tmp/awx_1447077_awxjs_pa/project/add_disk.yml:28
skipping: [localhost] => {}
META: 

TASK [Create and attach disk to VM] ****
task path: /tmp/awx_1447077_awxjs_pa/project/add_disk.yml:36
Using module file /tmp/awx_1447077_awxjs_pa/project/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_5I2P_S/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 238, in <module>
    from azure.mgmt.managementgroups import ManagementGroupsAPI as ManagementGroupsClient
ImportError: No module named managementgroups
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "ad_user": null, 
            "adfs_authority_url": null, 
            "api_profile": "latest", 
            "append_tags": true, 
            "attach_caching": "read_only", 
            "auth_source": "auto", 
            "cert_validation_mode": null, 
            "client_id": null, 
            "cloud_environment": "AzureCloud", 
            "create_option": null, 
            "disk_size_gb": 32, 
            "location": "brazilsouth", 
            "lun": null, 
            "managed_by": "server-00000-000000-001", 
            "name": "server-00000-000000-001-dsk01", 
            "os_type": null, 
            "password": null, 
            "profile": null, 
            "resource_group": "REDACTED0000000000000001", 
            "secret": null, 
            "source_uri": null, 
            "state": "present", 
            "storage_account_type": "UltraSSD_LRS", 
            "subscription_id": null, 
            "tags": null, 
            "tenant": null, 
            "zone": null
        }
    }, 
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on tower01.dcbr01.corp's Python /usr/bin/python2. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

TASK [Get facts for all managed disks managed by a specific vm] ****
task path: /tmp/awx_1447077_awxjs_pa/project/add_disk.yml:66
Using module file /tmp/awx_1447077_awxjs_pa/project/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk_info.py
Pipelining is enabled.
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_manageddisk_info_payload_Zwr4yO/ansible_azure.azcollection.azure_rm_manageddisk_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 238, in <module>
    from azure.mgmt.managementgroups import ManagementGroupsAPI as ManagementGroupsClient
ImportError: No module named managementgroups
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "ad_user": null, 
            "adfs_authority_url": null, 
            "api_profile": "latest", 
            "append_tags": true, 
            "auth_source": "auto", 
            "cert_validation_mode": null, 
            "client_id": null, 
            "cloud_environment": "AzureCloud", 
            "managed_by": null, 
            "name": "server-00000-000000-001-dsk01", 
            "password": null, 
            "profile": null, 
            "resource_group": "REDACTED0000000000000001", 
            "secret": null, 
            "subscription_id": null, 
            "tags": null, 
            "tenant": null
        }
    }, 
    "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on tower01.dcbr01.corp's Python /usr/bin/python2. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

PLAY RECAP *****
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=2    rescued=1    ignored=0
=====================================================================================
```

**Comment by Fred-sun** [comment]
@rcdlinux I am working in it！ Thank you very much!

**Comment by Fred-sun** [comment]
@rcdlinux This Data_disk is attached to a VM. So it failed when deleting. If we want to delete the datadisk, we need to unmout the datadisk and then delete it again. Thank you very much!

**Comment by Fred-sun** [comment]
@rcdlinux You can refer to the PlayBook below to dettach the data disk and then perform the delete task. Thank you very much!
```e.g.
 - name: deattach managed disk
   azure_rm_manageddisk:
     resource_group: "{{ resource_group }}"
     name: "{{ rpfx }}"
     managed_by: ""
     disk_size_gb: 1024
     attach_caching: read_only

 - name: Delete managed disk
   azure_rm_manageddisk:
       resource_group: "{{ resource_group }}"
       name: "{{ rpfx }}"
       state: absent

**Comment by rcdlinux** [comment]
Hi @Fred-sun,

I will ask to the team test changing the "rescue" session from the playbook that we are using and I will return with the answer soon!


Thank you for pointing me that!

**Comment by rcdlinux** [comment]
Hey @Fred-sun,

Just registering here to let you know it worked here with the customer automation.

Thank you very much!
