### ISSUE TITLE
azure_rm_functionapp "Operation returned an invalid status code 'Bad Request'"

### ISSUE THREAD

**Issue by it-kombinat** [ansible/ansible_collections_azure#724]
##### SUMMARY
When executing the module, an error message appears without any further information. When executing the same parameters with the az cli, the creation works, also the deletion afterwards with Ansible works.
```
- name: Create function app
  azure.azcollection.azure_rm_functionapp:
      resource_group: myresourcegrp
      name: myapp
      storage_account: myaccount
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_functionapp

##### ANSIBLE VERSION
```paste below
2.10.2
```

##### COLLECTION VERSION

```paste below
azure.azcollection 1.10.0
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

CloudShell in Azure / Ubuntu 20.04

##### STEPS TO REPRODUCE

```yaml
- name: Create function app
  azure.azcollection.azure_rm_functionapp:
      resource_group: myresourcegrp
      name: myapp
      storage_account: myaccount
```

##### EXPECTED RESULTS

Function App creation

##### ACTUAL RESULTS

```paste below
task path: /home/user/app.yaml:7
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: user
<127.0.0.1> EXEC /bin/sh -c 'echo ~user && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380 `" && echo ansible-tmp-1641830665.1394982-3448-137104891137380="` echo /home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380 `" ) && sleep 0'
Using module file /home/user/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py
<127.0.0.1> PUT /home/user/.ansible/tmp/ansible-local-33108pxes3px/tmp47aqt562 TO /home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/ /home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/opt/ansible/bin/python /home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py", line 102, in <module>
    _ansiballz_main()
  File "/home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_functionapp', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py", line 414, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py", line 410, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py", line 224, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 469, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py", line 319, in exec_module
  File "/opt/ansible/lib/python3.7/site-packages/azure/mgmt/web/operations/web_apps_operations.py", line 332, in create_or_update
    **operation_config
  File "/opt/ansible/lib/python3.7/site-packages/azure/mgmt/web/operations/web_apps_operations.py", line 280, in _create_or_update_initial
    raise models.DefaultErrorResponseException(self._deserialize, response)
azure.mgmt.web.models.default_error_response_py3.DefaultErrorResponseException: Operation returned an invalid status code 'Bad Request'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path,ANSIBALLZ_PARAMS)\n  File \"/home/user/.ansible/tmp/ansible-tmp-1641830665.1394982-3448-137104891137380/AnsiballZ_azure_rm_functionapp.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_functionapp', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.7/runpy.py\", line85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py\", line 414, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py\", line 410, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py\", line 224, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 469, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_functionapp_payload_94o28sy7/ansible_azure.azcollection.azure_rm_functionapp_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_functionapp.py\", line 319, in exec_module\n  File \"/opt/ansible/lib/python3.7/site-packages/azure/mgmt/web/operations/web_apps_operations.py\", line 332, in create_or_update\n    **operation_config\n  File \"/opt/ansible/lib/python3.7/site-packages/azure/mgmt/web/operations/web_apps_operations.py\", line 280, in _create_or_update_initial\n    raise models.DefaultErrorResponseException(self._deserialize, response)\nazure.mgmt.web.models.default_error_response_py3.DefaultErrorResponseException: Operation returned an invalid status code 'Bad Request'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by Fred-sun** [comment]
@it-kombinat There is no problem in my local test. According to the log, it is the parameter problem of your request. Could you please redefine the name and try again? Thank you very much!
```e.g.
    - name: Create a function app
      azure_rm_functionapp:
        resource_group: myResourceGroup
        name: functest0194
        storage_account: {{ your-storage-account }}

**Comment by it-kombinat** [comment]
@Fred-sun: We have found out that it only works with lowercase letters as function name.
(e.g.: myapp instead of Myapp)

**Comment by adthorn** [comment]
I have the same issue, I have lower case letters and but I do have dashes which are supported in ARM/BICEP.
    - name: Create a function app with app settings
      azure.azcollection.azure_rm_functionapp:
        name: "faw-{{subscode}}-{{appcode}}-{{envcode}}-{{azr_faw.function}}-{{location | regex_replace('us', '')}}-{{ '%03d' | format(azr_faw.instance|int) }}"
        resource_group: "{{azr_rg_name}}"
        subscription_id: "{{azr_subs_id}}"
        tenant: "{{tenant}}"
        secret: "{{secret}}"
        client_id: "{{client_id}}"
        storage_account: "{{azr_stfa_name}}"
        plan:
          resource_group: "{{azr_rg_name}}"
          name: "{{azr_aspw_name}}"
        tags:
            Description: "Function App {{azr_faw.function}}: For {{appcode}} - {{envcode}}"
            Subscription: "{{subscode |upper}}"
            AppCode: "{{appcode |upper}}"
            AppOwner: "{{appowner}}"
            Environment: "{{envcode |upper}}"
            ResourceType: "faw"
      register: azr_resource_output_faw
